fix: Removes gradient top on default card
ApollosProject/apollos-apps pull request #1584
Opened 2020-09-22 15:46 UTC by christinamegura

## DESCRIPTION
This PR removes the gradient top overlay on default cards.

### What does this PR do, or why is it needed?

### What design trade-offs/decisions were made?

### How do I test this PR?
Use `storybook` to navigate to default cards to review changes.

### What automated tests did you write?

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

2020-09-22 16:59 UTC, christinamegura commented
@vinnyjth, can you get this to pass unit tests? Or help me before Friday? I don't want to go down the test rabbit hole again

2020-09-22 17:28 UTC, vinnyjth requested changes

2020-09-22 17:28 UTC, vinnyjth commented on packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
>      overlayColor: theme.colors.black,
If we don't use `overlayType`, we probably don't need `overlayColor` :)

2020-09-22 17:28 UTC, vinnyjth commented on packages/apollos-ui-kit/src/DefaultCard/index.js
> -    overlayType: 'gradient-top',
Nice catch, changing this in both files :)

2020-09-22 17:55 UTC, vinnyjth commented
@christinamegura I believe you introduced an unintentional snap change to `AddPrayerScreenConnected`. Not sure how, but if you back it out I believe tests will pass fine.

2020-09-22 18:13 UTC, vinnyjth commented
![Simulator Screen Shot - iPhone 11 - 2020-09-22 at 14 10 54](https://user-images.githubusercontent.com/1637694/93920639-6fb00500-fcdd-11ea-8008-07bccdf86de9.png)

@christinamegura I think we'll need a little more work here, the `GradientOverlayImage` defaults to the `default` overlay if you don't specify an `overlayType`. We might have a `none` overlay type, or you'll have to find another way to turn off the overlay. Peeking at the code, I think there's a way ;)

2020-09-22 18:59 UTC, christinamegura commented on packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
>      overlayColor: theme.colors.black,
I totally had that removed at first, shucks. Changing now, thank ya!

2020-09-25 13:28 UTC, vinnyjth commented
@christinamegura When you get the tests passing again, throw the flag on and I'll give this another review :)

2020-09-25 18:03 UTC, vinnyjth commented
@christinamegura I think you need to update snaps again, then you should be good to go!

2020-09-28 15:15 UTC, vinnyjth approved these changes

2020-09-28 15:28 UTC, merged