feat: add date to content items
ApollosProject/apollos-apps pull request #1614
Opened 2020-10-14 14:12 UTC by christinamegura

## DESCRIPTION

### What does this PR do, or why is it needed?

### What design trade-offs/decisions were made?

### How do I test this PR?

### What automated tests did you write?

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

2020-11-18 17:52 UTC, christinamegura reviewed
@vinnyjth tests are passing locally but I'm seeing jest spit out a heuristic fragment matcher warning. Can you point me in the right direction to address this?

2020-11-18 17:52 UTC, christinamegura commented on packages/apollos-data-schema/src/index.js
> +    publishDate: String
@vinnyjth what is the difference between the `ContentNode` interface and the `ContentItem` interface?

2020-11-23 13:59 UTC, vinnyjth commented on packages/apollos-data-schema/src/index.js
> +    publishDate: String
`ContentNode` is the new interface that describes a `Node` that is "viewable" as a piece of "content". Pretty much means that it's something you can tap on and open and read, and it normally has an image, title ,and a bit of text.  

The `publishDate` probably doesn't belong on the `ContentNode`, but it does belong on the `ContentItem`. The `ContentItem` specifically describes `ContentItems` from Rock (or their equiv in other CMSes)

2020-11-23 13:59 UTC, vinnyjth commented on packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
> +    publishDate
Awesome way to get more test coverage! Nice work.

2020-11-23 14:30 UTC, vinnyjth requested changes

2020-11-23 14:30 UTC, vinnyjth commented on packages/apollos-data-connector-rock/src/content-items/resolver.js
> +      .split(/[-+]\d+:\d+/)[0],
Okay - this might be a bit funky so please let me know if it doesn't make any sense. 

1. Dates come back from Rock with no timezone attached, but they are in Eastern. 
2. When we parse dates with Moment, they default to UTC
3. If you call `.tz()` it changes the timezone to `Eastern`, moving the time 4 or 5 hours in one direction. 
4. Calling `format()` and then `split()` pops the timezone data back off the string. 

There's a reason we use the dance in some parts of the codebase, and I think it has to do with filtering with UTC dates, or sending dates from Rock back into Rock. 

All that to say - if you look at the API right now it's returning the exact same data that's in Rock. 

<img width="1748" alt="image" src="https://user-images.githubusercontent.com/1637694/99973573-e618c400-2d6d-11eb-8017-86121d4f70e9.png">

This won't be a good long term format for this field b/c devices in different time zones (or the server itself) will interpret that date as existing in it's own timezone. So Devices parsing that date in Central, will display the wrong time (off by an hour). If a server method was to try to use that `publishDate` dataSource method, it will parse that time as in UTC (and the time would be 4 hours off)

To fix this, you'll need to make sure two things are true. 

1. The string returned from the API has a timezone attached (look for a Z or a +/-) (`2018-05-08T00:00:00.000Z`)
2. The string returned from the API is about four hours different from the string returned in Rock. That's because the API should be returning UTC strings. 

I would investigate the `moment-timezone` `moment.tz(date, timezone)` methods to start :)

2020-11-23 16:08 UTC, christinamegura commented on packages/apollos-data-connector-rock/src/content-items/resolver.js
> +      .split(/[-+]\d+:\d+/)[0],
<img width="639" alt="Screen Shot 2020-11-23 at 10 47 34 AM" src="https://user-images.githubusercontent.com/52924611/99985644-3565f100-2d7c-11eb-9147-f28037e40361.png">

2020-11-24 13:50 UTC, vinnyjth commented
@christinamegura You're getting closer! 

There's one important tip I forgot to mention - when you run the server locally it runs in Eastern Timezone. When the server runs in the cloud, it's going to run in UTC. That's a frustrating fact of `node`. We can get around that by starting the server like this: `TZ=UTC yarn start` We should probably make that a default, sorry for not mentioning this earlier. 


So running the server in UTC, here's what I currently get 
<img width="1440" alt="Screen Shot 2020-11-24 at 8 43 49 AM" src="https://user-images.githubusercontent.com/1637694/100102442-9d2a4380-2e31-11eb-9ea4-ebac4ad84812.png">

It _looks_ correct, but in that screenshot I've pasted the date into the browser's `new Date()` function and you can see I end up with the 7th instead of the 8th, since my browser converts the UTC date into the equivalent eastern time, which is four hours (and thus a day) earlier. 

Going back to the requirements above,  you have a timezone attached do your date which is awesome! Now we just need that four hour offset. You had that with the code above, but it will only work if the server runs in the same time zone as Rock. The TZ=UTC should make it a little easier to test :) 

Thanks for your hard work @christinamegura! This timezone and date stuff is really frustrating, and very difficult to reason about and get right. I spent a lot of yesterday scratching my head and making sure I was thinking things through properly.

2020-11-24 13:51 UTC, vinnyjth commented
@christinamegura As for the tests, you'll probably need to either remove that `publishedAt` date from the `ui-fragments` package, or update all the tests that reference that fragment so their mocks include that field. You can probably remove the field from the fragment for now, since we aren't using it on the front end yet.

2020-11-24 16:04 UTC, christinamegura commented
@vinnyjth I think I finally got it! I'm not sure why my PR title is failing though 😬

2020-11-30 20:21 UTC, vinnyjth approved these changes
Nice work @christinamegura  :D

2020-12-01 15:44 UTC, conrad-vanl commented on packages/apollos-data-schema/src/index.js
> +    publishDate: String
@vinnyjth should we really use `String` here or should we make our own type? I'm thinking to enforce a certain convention or something

2020-12-01 17:01 UTC, vinnyjth commented on packages/apollos-data-schema/src/index.js
> +    publishDate: String
I have gone back and forth on this. Using `Date` is probably more correct, but I've seen more issues and problems arise from using a custom `scalar` and the `Date` field than I have seen it help.

2020-12-01 17:02 UTC, vinnyjth commented on packages/apollos-data-schema/src/index.js
> +    publishDate: String
@conrad-vanl Adding to that, we are already using `Strings` for the date we have in our Schema, so I'm fine with `String` going forward.

2020-12-10 16:13 UTC, merged