Comment improvements
ApollosProject/apollos-apps pull request #1693
Opened 2021-01-21 21:34 UTC by jimmyhogoboom

## DESCRIPTION

### What does this PR do, or why is it needed?

### What design trade-offs/decisions were made?

### How do I test this PR?

### What automated tests did you write?

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

2021-01-22 15:16 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/postgres/index.js
> +const options = process.env.NODE_ENV === 'test' ? { logging: false } : {};
good call ;)

2021-01-22 19:22 UTC, vinnyjth requested changes
Looking really good @jimmyhogoboom! I have two separate pieces of feedback around `user_flags` we'll need to figure out, but besides that this PR is ready to go!

2021-01-22 19:22 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/comments/model.js
> +const Visibility = {
I like how you are passing this Enum around

2021-01-22 19:22 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/user-flags/model.js
> +  modelName: 'user_flags',
should this be `user_comment_flags`? Just in case we ever support flagging for something like `prayers`. The other option is keep this as `user_comment_flags`, but change `commentId` to `nodeId` and `nodeType` so we can flag models polymorphicly.

2021-01-22 19:22 UTC, vinnyjth commented on packages/apollos-data-schema/src/index.js
> +    flagComment(commentId: ID!): UserFlag
Do you think we should return the `flag` here? I like how It's consistent with the other mutation signatures, but it might be more useful to return the `Comment`, the UI probably won't care about the specifics of the User Flag, and rather only care about current status of the FlaggedComment. 

If we have mutation return a UserFlag, we can also get rid of the `UserFlag` type and bring down the schema size a bit

2021-01-22 19:22 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/user-flags/__tests__/dataSource.js
> +describe('Apollos Postgres Comment Flags DataSource', () => {
Great tests!

2021-01-22 19:22 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/postgres/index.js
> +  process.env.NODE_ENV === 'test' ? { logging: false } : {};
THANK YOU for adding this. Makes running the tests in this module much nicer.

2021-01-22 19:26 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/user-flags/model.js
> +  modelName: 'user_flags',
Good call! I think I like `user_flags` with `nodeId` and `nodeType` better, as then we won't have to implement any new models/dataSources when we want to enable flagging for other objects. I'll make that change.

2021-01-22 19:27 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/user-flags/model.js
> +  modelName: 'user_flags',
I think I like that idea the most as well, sounds good :D

2021-01-22 19:28 UTC, jimmyhogoboom commented on packages/apollos-data-schema/src/index.js
> +    flagComment(commentId: ID!): UserFlag
Do you mean we can get rid of the `UserFlag` type if the mutation returns a Comment?

If so, then I agree, that would be more useful. I'll update this as well and remove that unnecessary type.

2021-01-22 19:31 UTC, vinnyjth commented on packages/apollos-data-schema/src/index.js
> +    flagComment(commentId: ID!): UserFlag
yep! typoed that sentence, I'll fix it so it reads in a way that makes sense

2021-01-22 21:19 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/postgres/index.js
> +  process.env.NODE_ENV === 'test' ? { logging: false } : {};
Yeah it was getting pretty old scrolling through all those messages to figure out why a test failed 😅

2021-01-25 16:27 UTC, jimmyhogoboom commented
@vinnyjth I can't manage to get these tests to work, and I'm not sure where to go from here. They all work just fine locally.

2021-01-27 15:53 UTC, vinnyjth approved these changes

2021-01-27 16:52 UTC, merged