feat: Follow data model
ApollosProject/apollos-apps pull request #1766
Opened 2021-02-25 22:50 UTC by jimmyhogoboom

Creates a FollowRequest data object along with a requestFollow mutation.

I also discovered when I tried to test the mutation that there was nothing creating a local database when just running the app, so I made my best attempt at implementing that.

Remaining todo:
- [ ] Create tests for the new feature
- [ ] Fix local database creation so the database exists before the sequelize instance is created. (Right now you have to run the templates app, stop it, then run again to get a good connection.)

2021-03-04 20:18 UTC, vinnyjth requested changes
Really good work here @jimmyhogoboom!

There's a few things I think we should work on before we merge, but overall we're really close. Biggest things are captured in the PR comments, but I'll repeat them here: 

- Module naming - is `FollowRequest` the best naming or should we try a different name?
- Mutation inputs - it would be great to use personIds across the board :) 
- Using `hasOne`, `belongsTo`  to setup relationship to `People` inside a `setupModel` function.

2021-03-04 20:18 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/follow-requests/model.js
> +    requestPersonId: DataTypes.UUID,
This could be a good opportunity to use the `setupModel` function :) You can see an example of what that looks like here: 

https://github.com/ApollosProject/apollos-apps/blob/master/packages/apollos-data-connector-postgres/src/campus/model.js#L23-L24

Note: you'll likely have to use the `({ as: requestPerson  })` option to rename the foreignKey

2021-03-04 20:18 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/follow-requests/resolver.js
> +    requestFollow: (root, args, { dataSources: { FollowRequest } }) =>
I love seeing simple resolvers like this :D

2021-03-04 20:18 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/people/dataSource.js
> +  async resolveId(id) {
This method looks very handy. I added some similar code in my `suggestedFollows` PR, and I think after this is merged I'll be able to use this code to enhance what I've done there :D

2021-03-04 20:18 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/follow-requests/__tests__/dataSource.js
> +import { sequelize, sync } from '../../postgres/index';
I love your tests! I really appreciate how thoroughly you test the code you write.

2021-03-04 20:23 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/postgres/index.js
> +  : localConnect();
Thanks!

2021-03-04 20:24 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/postgres/index.js
> +const isApollosId = (id) => {
Oh whoops, good catch!

2021-03-04 20:24 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/follow-requests/model.js
> +      type: DataTypes.BOOLEAN,
Very good call.

2021-03-04 20:25 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/follow-requests/dataSource.js
> +        return { followRequestId, following: true };
Oh nice, yeah good call.

2021-03-04 20:26 UTC, jimmyhogoboom commented on packages/apollos-data-schema/src/index.js
> +    ignoreFollowRequest(followRequestId: ID!): FollowRequestResult
That sounds good to me! I was honestly not sure what would be best for front end, glad to have your input!

2021-03-04 20:28 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/postgres/local-db.js
> +    await dbTestClient.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);
Yes, agreed. Migrations seem inevitable. I was noticing that the syncing step is taking longer the more tables we add, and it runs every time the app restarts after a change.

2021-03-04 20:29 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/follow-requests/dataSource.js
> +class FollowRequestDataSource extends PostgresDataSource {
Oh hey no worries, that's a great point. I was not in love the with name anyway 😅

Follow sounds good to me.

2021-03-04 20:31 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/people/dataSource.js
> +  async resolveId(id) {
Good to hear! I wasn't sure if this was going to be redundant, but I couldn't manage to find anything doing the same thing. Glad it works!

2021-03-04 20:31 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/follow-requests/__tests__/dataSource.js
> +import { sequelize, sync } from '../../postgres/index';
Thanks man!

2021-03-05 15:06 UTC, vinnyjth commented
@jimmyhogoboom just ping me when you want me to review again

2021-03-05 16:58 UTC, jimmyhogoboom commented
@vinnyjth Ok I think we're ready to go!

2021-03-05 19:37 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/follows/model.js
> +  sequelize.models.follows.belongsTo(sequelize.models.people, {
awesome :D

2021-03-05 19:38 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/follows/model.js
> +  sequelize.models.follows.belongsTo(sequelize.models.people, {
in the future we can pair on setting up hasManyThrough relationships using this table. that way we'll be able to get 
```
const person = await person.findById('xxxxxx');
const followers = await person.followers()
```

2021-03-05 19:39 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/follows/resolver.js
> +  FollowResult: {
What do you think about renaming this is as a follow as well?

2021-03-05 19:39 UTC, vinnyjth commented on packages/apollos-data-schema/src/index.js
> +  type FollowResult {
Mentioned this above, what do you think about renaming this as `Follow`?

2021-03-05 19:40 UTC, vinnyjth commented
Looking great @jimmyhogoboom! I think there's one more rename and then we can merge :)

2021-03-05 19:45 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/follows/resolver.js
> +  FollowResult: {
Sounds good!

2021-03-05 19:48 UTC, jimmyhogoboom commented
@vinnyjth Rename complete. Good to go?

2021-03-05 19:50 UTC, vinnyjth commented
> @vinnyjth Rename complete. Good to go?

I think so! I'mma run through one more time locally then we can merge.

2021-03-05 20:08 UTC, vinnyjth commented
![image](https://user-images.githubusercontent.com/1637694/110167968-839b7f00-7dc4-11eb-9ede-8827a0ff1253.png)

I think you need to `parseGlobalId` on the personId passed into the `requestFollow` mutation :)

2021-03-05 21:20 UTC, jimmyhogoboom commented
Oops, ok I was expecting either our internal Postgres PK id, or the Rock integer Id. I dunno why I didn't think of the global ids. I'll get that changed out herer

2021-03-05 21:38 UTC, jimmyhogoboom commented
@vinnyjth Will we need to run the id from the result of `parseGlobalId` through `resolveId`, or can we always expect a Postgres UUID there?

2021-03-08 13:30 UTC, vinnyjth commented
> @vinnyjth Will we need to run the id from the result of `parseGlobalId` through `resolveId`, or can we always expect a Postgres UUID there?
> 
> And should the `followId` returned in the result of these methods be a global id?

@jimmyhogoboom Let's avoid doing so currently, although I may eat my words. Easy enough thing to fix in a PR :)

2021-03-08 13:46 UTC, vinnyjth approved these changes
Nice work @jimmyhogoboom  :D

2021-03-08 13:46 UTC, merged