chore: Add GIN name index to optimize searching by name
ApollosProject/apollos-apps pull request #1805
Opened 2021-03-17 21:11 UTC by jimmyhogoboom

## DESCRIPTION
Speed up searching by full name in the people table.

### What does this PR do, or why is it needed?
This adds an index on `lower("firstName" || ' ' || "lastName")` to allow efficiently searching via full name like "Jimmy Hogoboom". Note that the input search term will need to be made lowercase ("jimmy hogoboom").

### How do I test this PR?
Try running `EXPLAIN ANALYZE SELECT "firstName" || ' ' || "lastName" FROM people WHERE lower("firstName" || ' ' || "lastName") LIKE '%vincent wilson%'` before and after applying this PR to see the speed difference.

2021-03-17 23:29 UTC, vinnyjth requested changes
![image](https://user-images.githubusercontent.com/1637694/111551645-0e7e6100-8757-11eb-9d96-5899a35c6dab.png)

Fantastic work @jimmyhogoboom! Elegant and speedy solution. a few nitpicks with the migration and then I think we're off to the races!

2021-03-17 23:29 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/people/migrations/003_add_names_index.js
> +  // no
😂 I love the idea of having this as the `down` for non-column migrations. However, we should probably play it safe and use `removeIndex` :) 

https://sequelize.org/master/class/lib/dialects/abstract/query-interface.js~QueryInterface.html#instance-method-removeIndex

2021-03-17 23:29 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/people/migrations/003_add_names_index.js
> +  await queryInterface.sequelize.query(
We have the option of using `addIndex` here. Which method do you prefer? 

https://sequelize.org/master/class/lib/dialects/abstract/query-interface.js~QueryInterface.html#instance-method-addIndex

2021-03-17 23:29 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/postgres/migrations/001_add_pg_trgm_extension.js
> +    'CREATE EXTENSION IF NOT EXISTS "pg_trgm";'
Awesome :D Crazy how these `pg` extensions work

2021-03-18 02:09 UTC, jimmyhogoboom commented on packages/apollos-data-connector-postgres/src/people/migrations/003_add_names_index.js
> +  await queryInterface.sequelize.query(
I honestly think it would be better to use `addIndex`, but I opted for this method purely in the interest of time. Maybe I'll work on the follow auto-accepting first, and if I get that done quickly enough I'll come back and update this.

2021-03-18 02:11 UTC, vinnyjth commented
Awesome, thanks for calling that out :) good prioritizing and I appreciate the compromise. I’ll take a quick stab at this tomorrow, and if I can’t solve it in 5 mins, we can merge it as is :D 

> On Mar 17, 2021, at 10:09 PM, Jimmy Hogoboom ***@***.***> wrote:
> 
> ﻿
> @jimmyhogoboom commented on this pull request.
> 
> In packages/apollos-data-connector-postgres/src/people/migrations/003_add_names_index.js:
> 
> > @@ -0,0 +1,13 @@
> +async function up({ context: queryInterface }) {
> +  await queryInterface.sequelize.query(
> I honestly think it would be better to use addIndex, but I opted for this method purely in the interest of time. Maybe I'll work on the follow auto-accepting first, and if I get that done quickly enough I'll come back and update this.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-18 15:29 UTC, vinnyjth approved these changes

2021-03-18 15:29 UTC, jimmyhogoboom commented
Nice!

2021-03-18 15:47 UTC, merged