feat: Update OneSignal to v4
ApollosProject/apollos-apps pull request #1935
Opened 2021-05-10 20:26 UTC by vinnyjth

Your best bet for testing this is pulling the companion PR and building an app for the phone, then sending yourself a push notification with a button on iOS, and confirming you see the button. 

You can add a button when sending a push through OneSignal here. 
![image](https://user-images.githubusercontent.com/1637694/118702108-806c3880-b7e2-11eb-8311-961d23d8f956.png)

2021-05-18 18:04 UTC, vinnyjth commented
Companion PR: https://github.com/ApollosProject/apollos-templates/pull/351

2021-06-07 15:38 UTC, redreceipt commented
@vinnyjth explain to me why this wouldn't be a breaking change. I want to say "no biggie" but if clients point to this version, their app will break, correct?

2021-06-07 15:40 UTC, vinnyjth commented
It is a breaking change :/ you also need to update the client with the template changes. You can't update templates without this change, and you can't update your package versions without having the code in templates. 

We could potentially "fix" that dependency by adding a bunch of try / catches around the existing code so it will safely try both the old and new code. What do you think?

2021-06-07 15:42 UTC, redreceipt commented on packages/apollos-ui-notifications/src/permissionUtils.js
> +  (await OneSignal.getDeviceState()).hasNotificationPermission;
since these are one-liners that simply use the OS SDK, I say we push this line to whatever is calling the `getPushPermissions` function and then deprecate and `console.warn` this and `getHasPrompted` function. Not helpful to abstract.

2021-06-07 15:44 UTC, vinnyjth commented on packages/apollos-ui-notifications/src/permissionUtils.js
> +  (await OneSignal.getDeviceState()).hasNotificationPermission;
👍  sounds good to me.

2021-06-07 15:48 UTC, redreceipt commented
> It is a breaking change :/ you also need to update the client with the template changes. You can't update templates without this change, and you can't update your package versions without having the code in templates.
> 
> We could potentially "fix" that dependency by adding a bunch of try / catches around the existing code so it will safely try both the old and new code. What do you think?

Unfortunately, I think it's the right thing to do. It will ensure that folks can upgrade past 2.19 to get some bug fix without having to fool with OS v4 if they don't need it.

2021-06-07 15:49 UTC, redreceipt requested changes
- make it non-breaking
- deprecate utility functions

2021-06-10 19:26 UTC, redreceipt commented on packages/apollos-ui-notifications/src/permissionUtils.js
> +const getPushPermissions = async () => {
same question with this file. seems smelly to keep catch with nothing all over the place.

2021-06-10 19:26 UTC, vinnyjth commented on packages/apollos-ui-notifications/src/Provider.js
> +      OneSignal.init(this.props.oneSignalKey, {
I wanted to separate the old/new code more clearly, and I liked the idea that an exception raised in the inital block would trigger our deprecation message.

2021-06-10 19:27 UTC, vinnyjth commented on packages/apollos-ui-notifications/src/permissionUtils.js
> +const getPushPermissions = async () => {
Same as above, it also felt messy calling two different implementations of OneSignal side by side. Seemed like this has an easy deprecation path moving forward, delete the second block and remove try/catch.

2021-06-10 19:31 UTC, redreceipt commented on packages/apollos-ui-notifications/src/permissionUtils.js
> +const getPushPermissions = async () => {
the only risk is if there's a legit problem with the old commands, we won't be properly notified.

2021-06-10 19:31 UTC, vinnyjth commented on packages/apollos-ui-notifications/src/Provider.js
> +      OneSignal.init(this.props.oneSignalKey, {
oh I feel dumb, I see what you're saying. So 

```
try {
 v4
 } catch {
   warn
   v3
 }
``` 

The only thing I don't like about this, is that if there's a legit issue with v4, we end up raising two warnings. v4 will throw an exception, and then v3 will throw an exception (since it's code doesn't exist). You'll be left with a `console.warn()` of the real error, and then an actual redscreen of v3 code failing to be called. I went this route to avoid that, and that's also why I let v3 fail silently.

2021-06-10 19:35 UTC, vinnyjth commented on packages/apollos-ui-notifications/src/Provider.js
> +      OneSignal.init(this.props.oneSignalKey, {
what I would prefer is 
```
if OneSIgnal.v3
{
code
} 

if OneSignal.v4
{
code
}
```

I could probably do that by checking for a property or function that only exists in v3.

2021-06-10 19:37 UTC, redreceipt commented on packages/apollos-ui-notifications/src/Provider.js
> +      OneSignal.init(this.props.oneSignalKey, {
I do like that the best by far. I don't like using try/catch blocks for things that you have already fully anticipated.

2021-06-10 19:38 UTC, vinnyjth commented on packages/apollos-ui-notifications/src/Provider.js
> +      OneSignal.init(this.props.oneSignalKey, {
same. I'll do that instead.

2021-06-10 20:01 UTC, vinnyjth commented
Thanks for your feedback @redreceipt, feeling way better about this PR than where it started.

2021-06-10 20:02 UTC, redreceipt commented on packages/apollos-ui-notifications/src/Provider.js
> +    if (OneSignal.setAppId) {
```suggestion
    if (OneSignal.setAppId && this.props.oneSignalKey) {
```

to avoid this and to make the prop optional

<img width="473" alt="Screen Shot 2021-06-10 at 3 59 49 PM" src="https://user-images.githubusercontent.com/2659478/121589567-36532d00-ca05-11eb-8ecf-8a86eba8bfec.png">

2021-06-10 20:03 UTC, redreceipt commented on packages/apollos-ui-notifications/src/Provider.js
> +    if (OneSignal.setAppId) {
actually it's gonna need to go one level up so when there's no prop, v3 code doesn't try to run

2021-06-10 20:06 UTC, vinnyjth commented on packages/apollos-ui-notifications/src/Provider.js
> +    if (OneSignal.setAppId) {
v3 doesn't error, so I think your change is good

2021-06-10 20:20 UTC, redreceipt commented
trying to test this but I may be missing something obvious, I can't even get a test notification to send to my sim. I've got `ONE_SIGNAL_KEY` defined and am just sending a new push to all devices on Apollos-Prototype

2021-06-10 20:25 UTC, redreceipt commented on packages/apollos-ui-notifications/src/Provider.js
> +    if (OneSignal.setAppId) {
well, if you're on v4 and don't pass the prop, it's gonna drop to v3 code and try to run `Onesignal.init` which will error because it doesn't exist.

2021-06-10 20:59 UTC, redreceipt commented on packages/apollos-ui-notifications/src/Provider.js
> +    if (OneSignal.setAppId) {
nevermind, it just comes through as an unresolved promise.

<img width="473" alt="Screen Shot 2021-06-10 at 4 58 51 PM" src="https://user-images.githubusercontent.com/2659478/121596272-39eab200-ca0d-11eb-9e36-35be0786fc2d.png">

2021-06-11 13:37 UTC, vinnyjth commented
> trying to test this but I may be missing something obvious, I can't even get a test notification to send to my sim. I've got `ONE_SIGNAL_KEY` defined and am just sending a new push to all devices on Apollos-Prototype

iOS Simulators can't receive push notifications :/

2021-06-16 19:50 UTC, redreceipt approved these changes

2021-06-16 19:50 UTC, merged