landing
ApollosProject/apollos-apps pull request #1980
Opened 2021-06-07 19:56 UTC by redreceipt

- chore: move landing screen to core
- text color

2021-06-11 13:44 UTC, vinnyjth commented on packages/apollos-ui-onboarding/src/slides/Landing/index.js
> +const BrandIcon = withTheme(({ theme, color }) => ({
I would give these names, just in case we want to override them individually.

2021-06-11 13:45 UTC, vinnyjth commented on packages/apollos-ui-onboarding/src/slides/Landing/index.js
> +  'ui-onboarding.Landing'
👍

2021-06-11 14:19 UTC, vinnyjth requested changes
Add names to the landing screen components, and then this is good to go!

2021-06-12 00:00 UTC, redreceipt commented on packages/apollos-ui-onboarding/src/slides/Landing/index.js
> +const BrandIcon = withTheme(({ theme, color }) => ({
good call. done.

2021-06-14 17:00 UTC, redreceipt commented
> Add names to the landing screen components, and then this is good to go!

done

2021-06-15 13:52 UTC, vinnyjth approved these changes
very rad

2021-06-15 14:02 UTC, merged