chore: remove yalc
ApollosProject/apollos-apps pull request #1991
Opened 2021-06-12 03:48 UTC by redreceipt

2021-06-15 13:15 UTC, vinnyjth commented on package.json
> -    "build:watch": "node ./scripts/watch.js",
We still need `yarn build build:watch` - otherwise changes aren't picked up when making API changes with `yarn api`

2021-06-15 13:15 UTC, vinnyjth commented on package.json
> -    "yalc": "^1.0.0-pre.35"
FINALLY :D

2021-06-15 13:16 UTC, vinnyjth requested changes
Need to keep `build:watch`, but otherwise looking great :D

2021-06-15 13:49 UTC, vinnyjth commented
> Need to keep `build:watch`, but otherwise looking great :D

I should add - we don't currently have `build:watch` integrated into `yarn api` but we need to :) Right now if you make a change in any of the `data-connector` packages, we end up needing to ether run `yarn lerna run build` to pick up those changes, or run `yarn api` again.

2021-06-17 00:19 UTC, redreceipt commented
I think the expectation now is that we run have to run `yarn start` (it does the watch script you're looking for) and then run `yarn api` in a separate window. they can't be sequential because we don't want any node processes to start in the background

2021-06-23 18:04 UTC, vinnyjth approved these changes

2021-06-23 18:13 UTC, merged