feat: Postgres Prayers
ApollosProject/apollos-apps pull request #2138
Opened 2021-08-19 20:37 UTC by tomthornton

In order to run, import `PrayerRequest` from `apollos-dataconnector-postgres` and remove the import from `apollos-dataconnector-rock` in the `index.postgres.js` file of your ApolloChurchApi

2021-08-19 21:01 UTC, vinnyjth commented
At a glance, looking great!

Remember tests, we’ll need them before we merge :) try to get 100% test coverage over the dataSource methods as a goal

> On Aug 19, 2021, at 4:52 PM, codecov[bot] ***@***.***> wrote:
> 
> ﻿
> Codecov Report
> 
> Merging #2138 (2f2b523) into master (1b92606) will decrease coverage by 0.35%.
> The diff coverage is 12.96%.
> 
> 
> 
> @@            Coverage Diff             @@
> ##           master    #2138      +/-   ##
> ==========================================
> - Coverage   75.77%   75.41%   -0.36%     
> ==========================================
>   Files         585      590       +5     
>   Lines        9072     9123      +51     
>   Branches     2225     2231       +6     
> ==========================================
> + Hits         6874     6880       +6     
> - Misses       1949     1990      +41     
> - Partials      249      253       +4     
> Impacted Files	Coverage Δ	
> ...-connector-postgres/src/action-algorithms/index.js	1.23% <0.00%> (+0.01%)	⬆️
> ...-data-connector-postgres/src/prayers/dataSource.js	0.00% <0.00%> (ø)	
> ...os-data-connector-postgres/src/prayers/resolver.js	0.00% <0.00%> (ø)	
> ...tgres/src/prayers/migrations/001_create_prayers.js	28.57% <28.57%> (ø)	
> ...ollos-data-connector-postgres/src/prayers/model.js	40.00% <40.00%> (ø)	
> ...connector-postgres/src/prayers/migrations/index.js	100.00% <100.00%> (ø)	
> ...ata-connector-rock/src/interactions/data-source.js	80.55% <100.00%> (+0.27%)	⬆️
> ... and 2 more		
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-08-20 16:20 UTC, tomthornton commented
@vinnyjth tests added!

2021-08-23 12:20 UTC, vinnyjth reviewed
Here's my initial round of feedback @tomthornton  :D Looking pretty good so far, I think the only major thing we need to figure out is how to make the `prayed_for` array not a JSONB field :) 

I'm going to test in the sim, and then I might have more feedback.

2021-08-23 12:20 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/__tests__/dataSource.test.js
> +  });
Actually I take that back! We don't have flagging :)We probably should though! Since Rock supports it. We can add a field in a follow up PR.

2021-08-23 12:20 UTC, vinnyjth commented on packages/apollos-data-connector-rock/src/interactions/data-source.js
> +    if (action !== 'PRAY') {
We'll likely have to be a bit more careful here :/ if we have this `action` skipping the `interaction` all of the rock folks are going to see their `Prayer` interactions drop off. Maybe we could do something (even if it's hacky) to figure out if it's a Rock or Postgres ID and then skip the `post` then? or even wrap the `post` in a try/catch

2021-08-23 12:20 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async getPrayerById(prayerId) {
You might be able to get away without this method by using the inherited `getFromId` method.

2021-08-23 12:20 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async incrementPrayed(prayerId) {
Is this working? I believe the function signature here (coming from the additional interactions) is an object of the form `{ id, __type, action }`

2021-08-23 13:28 UTC, vinnyjth requested changes
I think that's all the feedback I have :D thanks for your hard work Tom! PR is looking really good

2021-08-23 13:28 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/migrations/001_create_prayers.js
> +  await queryInterface.createTable('prayer', {
What do you think about naming this table `prayer_request`?

2021-08-23 13:28 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async byDailyPrayerFeed({ numberDaysSincePrayer = 3, limit = 10 }) {
I believe this `method` takes an optional `personId` argument that, when provided, returns _only_ prayers from that person. We'll need to implement that functionality to support this "My Prayers" feature. (Right now it's showing the same content as the "Pray for others" feature. 

![image](https://user-images.githubusercontent.com/1637694/130455436-bd2c380f-91fa-4cd4-a274-8334ccd4472e.png)

2021-08-23 14:27 UTC, tomthornton commented
@vinnyjth Thank you! I'll be working on those changes

2021-08-23 15:05 UTC, tomthornton commented on packages/apollos-data-connector-rock/src/interactions/data-source.js
> +    if (action !== 'PRAY') {
Yeah I figured this would be the case. I like the try/catch fix for now. Once they are shoveled back into rock it should still work.

2021-08-23 15:09 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/prayers/migrations/001_create_prayers.js
> +  await queryInterface.createTable('prayer', {
Sure that makes sense. And the join table `user_prayer` or just `prayer`?

2021-08-23 15:38 UTC, camrun91 commented
While you all are working on this @vinnyjth @tomthornton it would be awesome to have the ability to mark your own prayers as answered with an answer text Rock supports this currently. Also would be neat if you prayed for a prayer to get notified if it is marked answered. 

If I need to move this to discussions I can do that.

2021-08-23 15:40 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async incrementPrayed(prayerId) {
Yep it's working. Line 18 of the interactions data source in Rock takes the id out and passes it to the incrementPrayer function.

2021-08-23 15:48 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async incrementPrayed(prayerId) {
Ah, thanks I missed that. 👍

2021-08-23 15:58 UTC, tomthornton commented
@camrun91 yeah that sounds like a cool feature! We'll probably have to wait to implement that until after we've connected things back to rock.

2021-08-23 16:41 UTC, tomthornton commented
- Added `getCurrentPerson` to the People datasource... not sure if this is already accessible somewhere else
- Added joint table `person_prayed_for` and some foreign key constraints to help with deleting
- Updated tests

2021-08-24 01:11 UTC, vinnyjth commented
@tomthornton I think there's a few more review comments that might require changes. Do you want to take a look at those before I re-review?

2021-08-24 16:26 UTC, tomthornton commented
@vinnyjth ready for review now. I added the `personId` argument to `dailyPrayerFeed` and wrapped the interaction rock call with a try/catch.

2021-08-24 16:29 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async isPrayedFor({ prayerRequest, currentPersonId }) {
Have you considered using an `includes: [...]` to eager load this relationship? Might help reduce the number of queries significantly in a longer list of prayers :)

2021-08-24 16:30 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async isPrayedFor({ prayerRequest, currentPersonId }) {
If you add it as a default scope (see `content_items` with cover images`) you can know that the relationship will always be present

2021-08-24 16:38 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +  async isPrayedFor({ prayerRequest, currentPersonId }) {
Yep I was thinking the same thing, didn't know you could do that. I'll try it out.

2021-08-25 11:51 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/people/dataSource.js
>        return this.context.currentPostgresPerson.id;
Returning `id` here probably will result in a bug :)

2021-08-25 11:57 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +      .getPrayedUsers({
@tomthornton I think calling `.getPrayedUsers` here will re-run the query, rather than using the eager-loading that you added earlier with the `defaultScope`, Is that intentional?

2021-08-25 12:12 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/migrations/001_create_prayers.js
> +    users_prayed: {
@tomthornton You can delete `users_prayed` from the migration, I think :) if we had deployed this code, we would have to do another migration, but in this instance it's totally safe to simply remove it from the initial migration.

2021-08-25 12:13 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +      .getPrayedUsers({
Actually I can't prove this! So I think we're good.

2021-08-25 12:14 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/prayers/dataSource.js
> +      .getPrayedUsers({
😅 I realized I can't prove it, because this code isn't getting called anymore. You should be safe to remove it

2021-08-25 12:31 UTC, vinnyjth commented
@tomthornton 

Just three things to resolve and then we can merge this! Works well in the sim :) 

1. Dead code in the initial migration
2. Dead code in the dataSource `isPrayedFor` method
3. Tiny bug in `getCurrentPerson` logic

2021-08-25 14:59 UTC, tomthornton commented
@vinnyjth what is the dead code in the initial migration?

2021-08-25 15:54 UTC, vinnyjth approved these changes

2021-08-25 16:57 UTC, merged