feat: User progress from Postgres
ApollosProject/apollos-apps pull request #2151
Opened 2021-08-26 19:16 UTC by tomthornton

2021-08-30 18:08 UTC, tomthornton commented
@vinnyjth This is ready for review again. Added a test and the big SQL query we did plus the filters

2021-08-30 18:36 UTC, tomthornton commented
@vinnyjth this is ready for review again!

2021-08-30 20:07 UTC, vinnyjth reviewed
Some initial comments after looking over the code :) I'll run through the code in the app tomorrow and then wrap up.

2021-08-30 20:07 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
>    async getPercentComplete(model) {
I initially wondered if this method should be converted to pure SQL as well, but you have a really good approach here 👍

2021-08-30 20:07 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/interactions/dataSource.js
> +  async getInteractionsForCurrentUser({ actions = [], include = [] } = {}) {
rather than adding an additional arg, what do you think about adding a `queryArgs` argument similar to some our other methods that end up making `findAll` calls? Signature would become `getInteractionsForCurrentUser({ actions = []} = {}, queryArgs = {})` then you would spread `...queryArgs` inside the call to `findAll` :)

2021-08-30 20:07 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/utils/removeDuplicates.js
> +export default function removeDuplicates(array, basedOn) {
Do you still need this function?

2021-08-30 20:07 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/__tests__/dataSource.tests.js
> +  });
What do you think about adding a test over `getPercentComplete`? And maybe setup the data in such a way that we can be sure situations like duplicate interactions wouldn't cause issues :)

2021-08-30 20:07 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +      SELECT content_item.*
Nice work :D

2021-08-30 20:28 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/interactions/dataSource.js
> +  async getInteractionsForCurrentUser({ actions = [], include = [] } = {}) {
Yeah! I think that makes the most sense going forward

2021-08-30 20:28 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/utils/removeDuplicates.js
> +export default function removeDuplicates(array, basedOn) {
Nope. I'll remove it.

2021-08-30 20:29 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/content-items/__tests__/dataSource.tests.js
> +  });
Sure! That should be pretty easy given the other tests.

2021-08-31 13:02 UTC, vinnyjth requested changes
@tomthornton After testing in the app...

1. The "seriesInProgress" algorithm appears to be working perfectly. Nice work! 
2. The "You're all caught up" logic (driven by `upNext`) is working perfectly, again, nice work! 
3. The "Up Next" logic appears to be working through the items in a series backwards. Video to demo. Hopefully this is an easy fix, do you think we could write a test to capture this situation? It's been a pretty common one throughout the lifecycle of this feature. 

![2021-08-31 08 58 13](https://user-images.githubusercontent.com/1637694/131507084-a13aa6c3-42be-4b7b-95fb-2a5cc3d86a2d.gif)

2021-08-31 14:56 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/interactions/dataSource.js
> +  async getInteractionsForCurrentUser({ actions = [], include = [] } = {}) {
I think we stopped using this somewhere so I believe it's dead code. I'm going to delete it.

2021-08-31 17:07 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +    const childItems = await this.sequelize.models.contentItem.findAll({
Is there any reason you opted to switch from `getChildren`? I think this will be problematic in some cases since the sort order is undefined.

2021-08-31 17:14 UTC, vinnyjth requested changes
Really close @tomthornton :D I mentioned that we probally should try to use `getChildren` or, at least something that provides a sort order. I'll see if I can come up with a test case to demo that.

2021-08-31 17:14 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +    const currentPersonId = await Person.getCurrentPersonId();
It's a little odd that we call `Auth.getCurrentPerson()` above (and discard then ignore result) and then call it again here. We should problaly combine these calls, and use `await Person.getCurrentPersonId`. (which calls `await Auth.getCurrentPerson();`) under the hood

2021-08-31 17:14 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/interactions/dataSource.js
>          ...(actions.length ? { action: actions } : {}),
You'll want to make sure you spread the `...queryArgs` explicetly for the `{ where }` object, eg ` where { other stuff, ...queryArgs.where }`. Otherwise passing a where clause to `getInteractionsForCurrentUser` will override the entire `where` argument for `findAll`

2021-08-31 17:14 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +    const childItems = await this.sequelize.models.contentItem.findAll({
I'll come up with a test case that demonstrates why we need the sort order :)

2021-08-31 17:19 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +    const currentPersonId = await Person.getCurrentPersonId();
Yep I agree

2021-08-31 17:23 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +    const childItems = await this.sequelize.models.contentItem.findAll({
The reason I opted for to not use `getChildren` is because I thought it would be more accurate. `getChildren` goes through content-item-connections and I had thought that we just needed to pull from `parentId`. I had forgot they needed order. I'll just need to add in the content item connections to the tests.

2021-08-31 17:24 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +    const childItems = await this.sequelize.models.contentItem.findAll({
Sounds good 👍 You could even add `parentId` to the `queryArgs`  for `getChildren` and have the best of both worlds.

2021-08-31 17:56 UTC, tomthornton commented
@vinnyjth updated those tests and using `getChildren` now. Also fixed the weird Auth/Person thing. Are those tests covering enough or do we need to check for more things?

2021-08-31 17:58 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +      currentPersonId = await Auth.getCurrentPerson().then(({ id }) => id);
I believe that `getCurrentPerson` will return a rock Id. At this point. Also - why the `await` + `.then`?.

2021-08-31 18:02 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +      currentPersonId = await Auth.getCurrentPerson().then(({ id }) => id);
it was await to begin with. I guess I could just do `currentPerson.id`

2021-08-31 18:08 UTC, vinnyjth commented
@tomthornton Testing with the current data set, with an empty interactions table, I'm getting an "all caught up state" before visiting any of the child items. I'm also seeing this error in the console. 

![image](https://user-images.githubusercontent.com/1637694/131554008-4a8fd093-0f23-4dee-bfe8-2bb12db0d408.png)


```
Error: WHERE parameter "person_id" has invalid "undefined" value
    at PostgresQueryGenerator.whereItemQuery (/Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2258:13)
    at /Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:25
    at Array.forEach (<anonymous>)
    at PostgresQueryGenerator.whereItemsQuery (/Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2245:35)
    at PostgresQueryGenerator.generateJoin (/Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1711:24)
    at PostgresQueryGenerator.generateInclude (/Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1549:24)
    at PostgresQueryGenerator.selectQuery (/Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1183:34)
    at PostgresQueryInterface.select (/Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/dialects/abstract/query-interface.js:939:27)
    at Function.findAll (/Users/vincent/differential-projects/apollos/apollos-apps/node_modules/sequelize/lib/model.js:1753:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    ```

2021-08-31 18:18 UTC, tomthornton commented
@vinnyjth Ah, my fault I had assumed Auth was returning the right ID. Switched it to just use Person. It's working for me now.

2021-08-31 18:21 UTC, vinnyjth commented
@tomthornton Working for me also! 

Okay one more scenario to capture - if we write another test this would be a good use case. 

Given items 1, 2, 3, 4, 5
When I visit item 1, then item 3. When I hit check up next, 4 should be returned

Right now the logic is like this

Given items 1, 2, 3, 4, 5
When I visit item 1, then item 3. When I hit check up next, 2 is returned.

2021-08-31 19:25 UTC, tomthornton commented
@vinnyjth okay maybe this is done finally lol instead of adding multiple tests I did it all in one. I like how it captures the flow of user interaction.

2021-08-31 19:36 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/dataSource.js
> +    // If no item in the series has been interacted with
Nice! The comments are very helpful.

2021-08-31 19:37 UTC, vinnyjth commented on packages/apollos-data-connector-postgres/src/content-items/__tests__/dataSource.tests.js
> +  /*
we should probably comment this back in :)

2021-08-31 19:37 UTC, tomthornton commented on packages/apollos-data-connector-postgres/src/content-items/__tests__/dataSource.tests.js
> +  /*
I remembered right after. Should be good now.

2021-08-31 19:45 UTC, vinnyjth approved these changes
Nice work! Speedy and effective.

2021-08-31 19:59 UTC, merged