feat: tabs query
ApollosProject/apollos-apps pull request #2309
Opened 2022-01-03 23:05 UTC by redreceipt

lays the groundwork for dynamic tabs

2022-01-04 01:11 UTC, redreceipt commented on packages/apollos-data-schema/src/index.js
> +    tabs(campusId: ID, tags: [String]): [AppTab] @cacheControl(scope: PRIVATE)
```suggestion
    tabs(campusId: ID, tags: [String]): [Tab] @cacheControl(scope: PRIVATE)
```

2022-01-04 14:35 UTC, vinnyjth requested changes

2022-01-04 14:35 UTC, vinnyjth commented on packages/apollos-data-schema/src/index.js
> -  enum Tab {
You'll need to keep the enum :/ this will be bad news for existing clients updating. 

maybe do 

```
type AppTab
```

2022-01-04 16:17 UTC, redreceipt commented
dang i was afraid of that

2022-01-06 14:14 UTC, redreceipt commented
@vinnyjth this is ready to look at again

2022-01-10 16:03 UTC, vinnyjth approved these changes

2022-01-10 21:18 UTC, merged