feat: adds dynamic tabs
ApollosProject/apollos-apps pull request #2348
Opened 2022-01-25 17:15 UTC by redreceipt

2022-01-25 17:23 UTC, redreceipt commented
@conrad-vanl @vinnyjth this is close but getting this strange behavior, tabs are "sticking". I knew the tab navigator could present problems like this but my react native knowledge is lacking. Any ideas on what could cause this?

![Kapture 2022-01-25 at 12 16 41](https://user-images.githubusercontent.com/2659478/151026511-e2e50aec-0716-48de-bfe2-8b3b03ecc6fb.gif)

2022-01-25 20:58 UTC, redreceipt commented
it has to do with this, it's overwriting the home feature feed features in apollo cache with the prayer tab features, just don't know why...

<img width="1664" alt="Screen Shot 2022-01-25 at 3 57 38 PM" src="https://user-images.githubusercontent.com/2659478/151058599-a16c2130-2073-4e2e-81a0-80059c45db51.png">

2022-01-25 21:05 UTC, vinnyjth commented
@redreceipt most likely the ids. check that you are .

- fetching the ids for feature feeds
- that those ids are distinct (and aren't just base64ed [object Object] or soemthing)

2022-01-25 21:17 UTC, redreceipt commented
I’m logging them and they are unique and look ok

Sent from my iPhone

> On Jan 25, 2022, at 4:05 PM, Vincent Wilson ***@***.***> wrote:
> 
> ﻿
> @redreceipt most likely the ids. check that you are .
> 
> fetching the ids for feature feeds
> that those ids are distinct (and aren't just base64ed [object Object] or soemthing)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-01-25 22:27 UTC, redreceipt commented
@vinnyjth is typename potentially also required because of how we store items in the cache?

2022-01-27 05:19 UTC, conrad-vanl commented
@redreceipt as much as I really would like to push this PR through, I think we should probably pause it (and not let willow creek hold up because of it). As long as we can easily "Add" tabs on the api layer, having the frontend be a little more static isn't horrible for now. I'd like to dig into it more during cooldown perhaps.

2022-01-28 14:33 UTC, redreceipt commented
@conrad-vanl no further work is required, this is ready for review. do you still want to wait to merge?

2022-02-03 15:46 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +      icon
Do we have error handling if the icon doesn't exist?

2022-02-03 15:47 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +  if (loading || error) return null;
So during loading and error states nothing is rendered? HMW improve that?

2022-02-03 15:48 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/TabsConnected/Tabs.js
> +          screenOptions:
I think this should probably be `options` instead of `screenOptions`

2022-02-03 15:50 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/TabsConnected/Tabs.js
> +            title === 'Home'
What if the "home" tab isn't called `home`? I think my biggest concern with this PR is losing easy configurability of tab headers/containers and such. 🤔 How would we put a search button on non home tabs?

2022-02-03 15:52 UTC, conrad-vanl requested changes
Left some comments/thoughts. I'm still conflicted on this approach. I don't disagree about the idea of letting API tell the app which tabs should be shown, but overall this approach creates quite a bit of abstraction and loses some customizability. 

Part of me wonders if we should define a handful of tab "types" that have pre-configured things like the header bar, tab bar icon, and such. A little more restriction, a little less abstraction. But I also don't know if I'd like that either.

Edit: Answer my questions above and we can go from there, I'm not ruling out this approach yet. Just want to consider some of these angles, particularly how the tabs are configured: title, icon, navigation header, etc.

2022-02-03 16:02 UTC, redreceipt commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +const TabsConnected = ({ hasCampus }) => {
prop overrides

2022-02-03 16:02 UTC, redreceipt commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +  if (loading || error) return null;
activity indicator?

2022-02-03 16:04 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +  if (loading || error) return null;
Activity indicator and <ErrorCard /> at minimum I think. It would be nice to show placeholder state though.... placeholder tabs and placeholder feed. This is a pretty big change at the root level that everyone will experience, and I want to make sure the resulting UX is solid.

2022-02-03 16:05 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +const TabsConnected = ({ hasCampus }) => {
Another example then I think of my worries on how this is abstracted. What if only some of the tabs are campus specific? What does `hasCampus` do exactly?

2022-02-03 16:07 UTC, redreceipt commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +const TabsConnected = ({ hasCampus }) => {
passes `campus` as an arg to the `tabs` query for caching purposes. but we've pretty much moved that to the back end now so that functionality could probably be deprecated

2022-02-03 16:14 UTC, conrad-vanl commented
I think I'd sum up my concerns like this:

Right now, the frontend completely defines _which_ tabs are shown and _how_ they are shown. The backend just defines what data/content is shown on each tab.

This PR attempts to move the _which_ to the API layer, but the _how_ is lost. There's some attempts to keep the _how_, such as a hard code of "home" overrides if the tab is "titled" `Home`. But a title is more of a "what" and not a _how_, and so I think the contract is lost. The "title" and "icon" moving to the API layer indicates to me that there might be a goal to move a lot of the configurability to the API-layer, but I think that can get messy too. 

HMW let the API cleanly define "what" tabs should be shown, and the frontend still has a solid handle on the "how"?

One idea that I mentioned above is creating tab types. Similar to what we do with different content item types.... then the frontend can cleanly control how tabs are presented based on its type. If we were to go this route, I'd want to question how these types would be taxonomied: are they named based on the "type" of content? (Similar to our content types). `Giving`, `Media`/`Watch`, etc. Or are they named based on how the tab is "presented" - such as expressing how the header is setup and such. 

Also, based on pain points we've had from our strict content type naming, I'm not saying I like this approach yet, I'm just trying to call out the potential cons I'm seeing to this PR and would love your thoughts @redreceipt

2022-02-03 21:32 UTC, redreceipt commented
@conrad-vanl Yep! All very valid. I think I have an idea that aligns with our current theming process and allows for complete customization while providing sane defaults. I give you `ApollosConfig.TABS` what do you think??

![Group 1](https://user-images.githubusercontent.com/2659478/152432272-14c3640b-a5f2-4b93-8a94-7dd53b7139c0.png)

2022-02-03 21:36 UTC, redreceipt commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +  if (loading || error) return null;
added activity indicator. would love to work in loading states in a separate PR

2022-02-03 21:36 UTC, redreceipt commented on packages/apollos-ui-connected/src/TabsConnected/Tabs.js
> +          screenOptions:
done

2022-02-03 21:36 UTC, redreceipt commented on packages/apollos-ui-connected/src/TabsConnected/Tabs.js
> +            title === 'Home'
solved

2022-02-03 21:39 UTC, redreceipt commented on packages/apollos-ui-connected/src/TabsConnected/index.js
> +      icon
yes

2022-02-25 03:44 UTC, redreceipt commented
@conrad-vanl what do you think about my latest comment and changes here?

2022-03-24 14:29 UTC, redreceipt commented
Ping

2022-04-18 14:23 UTC, redreceipt commented
@conrad-vanl can you take a look at my latest comment and changes here? I'd really like to move template zero forward to get ready for scale cycle goals and this is an important step

2022-05-05 18:48 UTC, conrad-vanl commented
I'm sorry, I don't have the mental capacity / mind space to look at this today. I might be able to dig into it tonight or on Friday. @vinnyjth if you do have capacity, I trust your opinion here too and seeing whether my previous comment is properly addressed .

@redreceipt going forward if I'm slow to respond on GitHub ping me on slack. I don't always read my GitHub notifications very well

2022-05-05 19:46 UTC, vinnyjth approved these changes
I'm cool with this. 

I see @conrad-vanl's concerns, and while I don't think you've quite addressed them @redreceipt I think you've left the doors wide open to provide a more "packaged" experience using retool or other higher level configuration. 

I like the idea that our database has some pretty low level tools, but we're able to abstract them out into templated concepts using retool or scripts.

2022-05-05 22:39 UTC, merged