feat: Scripture Updates
ApollosProject/apollos-apps pull request #2582
Opened 2022-07-25 19:10 UTC by calebpanza

## Motivation
In preparation for the launch of Daily Habits, we're giving the Scripture Feature a splash of paint. This is a first round of edits that will ultimately lead to us enabling Journals to be viewed/written directly on a Scripture.

| Platform | Scripture Feature | Scripture Single |
| --- | --- | --- |
| iOS | <img width="248" alt="Screen Shot 2022-07-25 at 12 31 27 PM" src="https://user-images.githubusercontent.com/45076058/180855641-ae6a5964-3b8c-41ad-aea3-9d7d320c01a6.png"> | <img width="246" alt="Screen Shot 2022-07-25 at 12 31 05 PM" src="https://user-images.githubusercontent.com/45076058/180855672-eb91dfd6-2770-48b7-96db-44cfe0ed492f.png"> |
| iPadOS | <img width="623" alt="Screen Shot 2022-07-25 at 1 48 48 PM" src="https://user-images.githubusercontent.com/45076058/180855709-699b1fef-22e2-4f48-a8b2-1824a181985f.png"> | <img width="619" alt="Screen Shot 2022-07-25 at 1 49 29 PM" src="https://user-images.githubusercontent.com/45076058/180855733-7eb04b89-7529-4e6b-b2cc-7706906b09c2.png"> |
| Android | ![Screenshot_20220725-145621](https://user-images.githubusercontent.com/45076058/180855789-ba8ad5ac-da33-42b1-9b21-6b18b10943fd.png) | ![Screenshot_20220725-145936](https://user-images.githubusercontent.com/45076058/180855773-b9b94c8f-ad65-4524-8810-b340d6c512a8.png) |

2022-07-25 19:11 UTC, calebpanza commented
Waiting for an API branch to get merged before marking this as ready.

I know there's a slight visual issue with the Android Scripture View, but it's minimal enough that I'm not gonna worry about it right now. During cooldown, I'll come back to it.

2022-08-01 15:41 UTC, vinnyjth commented on packages/apollos-ui-connected/src/hooks/useDeleteScriptureJournal.js
> +    client.cache.gc();
oh cool

2022-08-01 15:46 UTC, vinnyjth commented on packages/apollos-ui-connected/src/features/ScriptureFeature.js
> +  return scriptures.map((scripture, i) => (
what's `i` for?

2022-08-01 15:48 UTC, redreceipt commented on packages/apollos-ui-connected/src/CommentListFeatureConnected/__snapshots__/CommentListFeatureConnected.tests.js.snap
> +                  color="#c64f55"
Should there be changes to the comment list feature?

2022-08-02 21:20 UTC, redreceipt commented on packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/__snapshots__/ContentSingleFeaturesConnected.tests.js.snap
> +exports[`ContentSingleFeaturesConnected should render with nodeId 1`] = `
this snap doesn't look right

2022-08-04 17:00 UTC, vinnyjth requested changes
hey @calebpanza! looking really good overall. Two UX issues I ran into

- The "Finish" but
![2022-08-04 12 53 37](https://user-images.githubusercontent.com/1637694/182908170-d0ceda4a-6c0c-41ec-94d3-22f92906d67a.gif)
ton is hidden behind the journal screen. maybe we could could add some padding to the bottom of the scripture screen if there's a journal feature. 

- When I'm closing the journal feature, it's easy to accidentally close the entire scripture experience (I've actually never managed to close "just" the journal experience). 
![2022-08-04 12 55 14](https://user-images.githubusercontent.com/1637694/182908419-8615c0f5-5955-46b1-add0-4ed01586685b.gif)

2022-08-04 19:21 UTC, calebpanza commented on packages/apollos-ui-connected/src/ScriptureScreenConnected/ScriptureJournals/AddJournal.js
> +  useLayoutEffect(() => {
Admittedly not my code. Lol. Stole it from the docs on the bottom sheet module

2022-08-04 19:22 UTC, calebpanza commented on packages/apollos-ui-connected/src/ScriptureScreenConnected/ScriptureJournals/JournalFeed/CommentWithActions.js
> +        { title: 'Edit Journal', systemIcon: 'square.and.pencil' },
Oh yes! Welcome to the magical world of system icons and SFSymbols! Lol. Seriously LOVE how Apple and Swift is handling iconography in their codebase.

2022-08-04 19:23 UTC, calebpanza commented on packages/apollos-ui-connected/src/ScriptureScreenConnected/ScriptureJournals/JournalFeed/CommentWithActions.js
> +  const contextMenu = useMemo(() => {
Love that idea!

2022-08-04 19:24 UTC, calebpanza commented
@vinnyjth such great feedback! Thanks for catching those. I'm working through resolutions to them now.

2022-08-04 19:32 UTC, redreceipt commented on packages/apollos-ui-connected/src/ScriptureScreenConnected/ScriptureJournals/JournalFeed/CommentWithActions.js
> +                  onPress: () => null,
will this make the alert go away?

2022-08-05 14:08 UTC, calebpanza commented
@vinnyjth here is a demo of those changes resolved. The code is a bit "cute" but it works! Lol

https://user-images.githubusercontent.com/45076058/183094344-83c77e3e-25ee-41b9-b27e-ec961d7d59e0.mp4

@redreceipt that method wasn't necessary and everything functions the same without it, so I removed it

2022-08-05 15:29 UTC, redreceipt commented
snaps failing

2022-08-05 15:55 UTC, camrun91 commented
OK Couple of things I am seeing here. I am expecting touching the drawer to open I think I make this assumption because it looks and feels like a text box and I am anticipating input there. 
I would suggest making this part touchable and making it so it opens the drawer. What do you all think?
![Screen Shot 2022-08-05 at 10 51 55 AM](https://user-images.githubusercontent.com/16566029/183115048-47639155-4abc-4e62-8c50-bfb4c56bfee0.png)

2022-08-05 15:59 UTC, vinnyjth commented
> I would suggest making this part touchable and making it so it opens the drawer. What do you all think?

I made the same mistake 😂  I agree it should be touchable.

2022-08-05 16:02 UTC, camrun91 commented
hahaha also make the text open up the editng area lol took me a bit to realize I had to hit the profile thing lol

2022-08-05 16:03 UTC, calebpanza commented
https://user-images.githubusercontent.com/45076058/183116583-f29dbba3-c0db-4e45-859f-2deb8dea7b66.mp4

2022-08-05 16:09 UTC, camrun91 commented
@calebpanza what if when there is a journal that section says "see what others are saying." or something like that. Then touch that it opens the drawer to see the journals. Then when it is open tapping what stands out to you or profile icon pops you over to the entry view?

2022-08-05 16:13 UTC, calebpanza commented
@camrun91 that's what it should be doing currently 😉 add a journal written by someone else in the dB to see all 3 states

2022-08-05 16:14 UTC, redreceipt commented
text is hard to see in dark mode
![Simulator Screen Shot - iPhone 13 - 2022-08-05 at 12 13 48](https://user-images.githubusercontent.com/2659478/183118440-05160e84-be9a-44f5-bbf3-7272979761cc.png)

2022-08-05 16:21 UTC, camrun91 commented
> @camrun91 that's what it should be doing currently 😉 add a journal written by someone else in the dB to see all 3 states

right now the drawer only opens on swipe or touching the profile or the "input area" tapping either of those kicks you to the entry screen.

2022-08-05 17:12 UTC, redreceipt approved these changes
very nice :)

2022-08-05 17:13 UTC, redreceipt commented
@vinnyjth have the changes you want been addressed?

2022-08-05 17:36 UTC, vinnyjth commented
> @vinnyjth have the changes you want been addressed?

@redreceipt based on the videos I saw above, absolutely

2022-08-05 17:37 UTC, vinnyjth approved these changes

2022-08-05 17:37 UTC, merged