feat: Community Single
ApollosProject/apollos-apps pull request #2646
Opened 2022-08-24 17:04 UTC by calebpanza

## Motivation
This PR introduces the baseline styling for the Community Single. 

## Approach
The API is still in progress, so this PR introduces and explicit cache-loading that mocks the desired data structure. This should help 1. get UI out for review quicker and 2. give @camrun91 an easy way to see what the UI is expecting to make sure API design is in alignment.

Per conversations with @vinnyjth and @redreceipt in Basecamp, this PR localizes the Community Single hooks to the CommunitySingleConnected directory.

## Caveats
This PR does _not_ include the Social Feed. In order to keep the PR as small as possible, I've limited the PR to just the main content that describes a Community Single

Light Mode was not explicitly designed for in Figma, so this is a 1-1 inversion of the desired Dark Theme (I think it looks fine for the time being and should not keep us from merging the PR. @conrad-vanl can review and make revisions in Figma and we can push out subsequent `patch` PR's for micro-level changes)

This PR uses _only_ the existing UI Kit components and is not a perfect 1-1 recreation of Figma. This is because I will be working on UI Kit 2.0 in the next week or so. Once that work is completed, a `chore` PR will be pushed out that re-implements this screen as our first screen fully driven by UI Kit 2.0. At that time, it'll match the Figma mocks 1-1. This is just to make ample time in the cycle for UI Kit 2.0 _and_ not risk Community Cycle goals.

## Testing
Pull up the mobile app and connect to prod's dB. Load up the Community Tab and press into the Community. Your cache will auto-load with the test data and you'll be good to go!

In order to test loading and error states, manually update return values in the `useCommunitySingle` hook.

## Screenshots

| | Light Mode | Dark Mode |
| --- | --- | --- |
| Current User is not a Member | ![non_member_state](https://user-images.githubusercontent.com/45076058/186479115-0baa5de4-2b42-466a-80a6-aaa2098bc644.png) | ![non_member_state](https://user-images.githubusercontent.com/45076058/186479268-c745d82c-df09-464c-9a01-fcb6e0f3915c.png) |
| Current User is a Member | ![member_state](https://user-images.githubusercontent.com/45076058/186479316-31513c64-d548-4872-8639-55606facad71.png) | ![member_state](https://user-images.githubusercontent.com/45076058/186479344-2553142b-683c-49ec-894d-2d08aaa52ead.png) |
| There are No Members in the Community | ![no_members](https://user-images.githubusercontent.com/45076058/186479406-c4167086-54a7-4365-a7e4-a716c12b3cc0.png) | ![no_members](https://user-images.githubusercontent.com/45076058/186479442-e27a6489-40b9-47dd-adca-99b583ebe2f2.png) |
| Loading State | ![loading_state](https://user-images.githubusercontent.com/45076058/186479486-2ef0f917-ec2d-482d-a982-5d5179bea5c2.png) | ![loading_state](https://user-images.githubusercontent.com/45076058/186479513-94855ac9-a3ce-4bbe-b7f4-f304cd3d5709.png) |
| Error State | ![error_state](https://user-images.githubusercontent.com/45076058/186479558-dc39d698-aced-495d-b4aa-7422b4ab0d70.png) | ![error_state](https://user-images.githubusercontent.com/45076058/186479585-43a5d35a-e0aa-4d1e-94b9-ebf354cbe47f.png) |

2022-08-25 15:49 UTC, conrad-vanl commented
<img width="560" alt="Screen Shot 2022-08-25 at 11 49 27 AM" src="https://user-images.githubusercontent.com/103927/186711438-bd790a48-7a9f-4a61-8060-88ca8c4ba0e1.png">

Would it be hard to get the user count up against the button, instead of spread out / space-between?

2022-08-25 16:19 UTC, calebpanza commented
> What's the deal with the green outline on this button?

I didn't notice that until after the screenshots were taken. It should be resolved in the simulator, though

> Would it be hard to get the user count up against the button, instead of spread out / space-between?

No not all! I can super easily make that switch

2022-08-25 16:24 UTC, calebpanza commented
@conrad-vanl here we go!
![Simulator Screen Shot - iPad Air (5th generation) - 2022-08-25 at 12 22 11](https://user-images.githubusercontent.com/45076058/186718625-c86438de-28e3-48e6-bba7-d54ff7403417.png)

2022-08-25 16:25 UTC, calebpanza commented
Double checked on that phantom border. We're all set now!

2022-08-26 13:41 UTC, conrad-vanl commented
Could you do an updated visual/video demo walking through the flows this PR introduces? Maybe for Visual PRs that could be a good deliverable so that someone like me can review design implementation without having to run it locally :)

2022-08-26 13:44 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/Details.js
> +const NeutralButtonIcon = withTheme(({ theme }) => ({
Is the intention to replace these with non-customized/styled components after Button is refactored?

2022-08-26 13:46 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/Details.js
> +          {currentUserIsMember && (
I know this is common practice and web land, but I'm curious if it can still cause issues in react-native land. 

What are the possible values of `currentUserIsMember`? Whatever falsey value of `currentUserIsMember` will get returned and react-native will try to render it. If it could ever be an empty string for example, react-native will throw an error

2022-08-26 13:47 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/TabNavigator/TabBar.js
> + * TabBar.js
Do you expect to pull this `TabNavigator` out of just Community?

2022-08-26 13:50 UTC, conrad-vanl commented
I'll let @vinnyjth do the primary code review but from my perspective so far the visuals look pretty good. I'd love to see a video walk through of the final state.

My only other thought re: code is what structures do we have setup that's planned to stay, and what structures are setup that's planned to be moved/refactored soon? I know @calebpanza wants to refactor a lot of the UI into `/mobile`, so I assume some of the styled buttons and such will be refactored once that's done. Another thought I had is it looked like everything is setup within `ui-connected` and new components introduced within just this `Community` folder structure. I wonder if it's intended for those things to stay there long term or get moved as well soon.

2022-08-26 13:53 UTC, calebpanza commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/TabNavigator/TabBar.js
> + * TabBar.js
Yeah, I think so. I really like the way that it landed. Setting it up as its own file was just a personal organizational choice. When the component landed as well as it did, I got to thinking that it'll probably be worth breaking out into its own reusable item inside the `mobile/components` dir (after the restructure)

2022-08-26 13:55 UTC, calebpanza commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/Details.js
> +          {currentUserIsMember && (
Oh I see. Yeah I can either wrap it in a `Boolean()` or even just break it out into its own rendering function. That's not a bad call. The data provider will guarantee that it's always a boolean, but without Typescript I see how this does lead to a vulnerability.

2022-08-26 13:56 UTC, calebpanza commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/Details.js
> +const NeutralButtonIcon = withTheme(({ theme }) => ({
Yeah exactly. I used only (mainly) the HOC's and our UI components cause I was able to crank it out crazy fast that way

2022-08-26 16:23 UTC, vinnyjth requested changes
This looks great overall! 

I'm not too worried about leaving this in ui-connected. It all needs to move over to `mobile/src` eventually, but building out here won't make that transition that much harder.

2022-08-26 16:23 UTC, vinnyjth commented on templates/mobile/package.json
> +    "ipados": "react-native run-ios --simulator=\"iPad Air (5th generation)\"",
win! thanks for adding this

2022-08-26 16:23 UTC, vinnyjth commented on packages/apollos-ui-connected/src/CommunitySingleConnected/hooks/useCommunitySingle.js
> +const useCommunitySingle = (id) => {
this approach of using the cache is a good compromise. nice work!

2022-08-26 16:23 UTC, vinnyjth commented on packages/apollos-ui-connected/src/CommunitySingleConnected/hooks/useCommunitySingle.js
> +    loading: queryLoading || mutationLoading,
should these be the same loading state? I imagine there's a future where you use the same hook to drive mutations and queries, and I feel it would be a bit odd if you showed a feed loading state when you join/leave.

maybe I'm wrong about that though

2022-08-26 16:23 UTC, vinnyjth commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/TabNavigator/TabBar.js
> +          const label =
nested ternaries can be so hard to parse 😅 

what about an array operation instead? 
```
const label = [options.tabBarLabel, options.title, route.name].filter(Boolean)[0]
```

2022-08-26 16:23 UTC, vinnyjth commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/MembersPreview.js
> +    { v: 1e3, s: 'K' },
neato!

2022-08-26 16:29 UTC, calebpanza commented on packages/apollos-ui-connected/src/CommunitySingleConnected/hooks/useCommunitySingle.js
> +    loading: queryLoading || mutationLoading,
Yeah that's a good callout. The UI will take into consideration both if data exists _and_ if there is a loading state. Buttons, though, will be considered disabled anytime there is a loading state. So I was thinking of maybe passing in a `mutationLoading` or `queryLoading` at some point if I need to be able to respond specifically to one of those scenarios. In practice, though, I found myself using `isLoading={queryLoading || mutationLoading}` on each component and figured it was worth consolidation

2022-08-26 16:30 UTC, calebpanza commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/TabNavigator/TabBar.js
> +          const label =
tbh I ripped this straight outa the React Navigation Docs and only customized the visuals. I would be more than happy to make that adjustment, though. I think that suggested approach is really smart!

What's the benefit to that vs `const label = options.tabBarLabel ?? options.title ?? route.name`?

2022-08-26 16:31 UTC, calebpanza commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/MembersPreview.js
> +    { v: 1e3, s: 'K' },
#StackOverflow. Lol

2022-08-26 16:32 UTC, calebpanza commented
@conrad-vanl per your request, here is an updated [demo](https://www.loom.com/share/6c5c7a940876442ba305623e9c8a0b54) of the UI in action.

The first 2 minutes walk through the UI states that are built out, and then the last bit of it explains the dev approach and how I was planning to integrate UI Kit 2.0 not the mix.

2022-08-29 14:12 UTC, calebpanza commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/Details.js
> +          {currentUserIsMember && (
I went ahead and just updated the rendering to be a memoized function so it's a bit safer/more explicit.

2022-08-29 14:55 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/CommunitySingleConnected/components/TabNavigator/TabBar.js
> +          const label =
TIL `??`

2022-08-29 14:59 UTC, vinnyjth approved these changes

2022-08-29 15:03 UTC, redreceipt approved these changes

2022-08-29 16:57 UTC, merged

2022-08-29 18:24 UTC, conrad-vanl commented
Watched the video. left a few minor comments on the loom but looking good!