chore: cleans up UpNext button
ApollosProject/apollos-apps pull request #2647
Opened 2022-08-27 15:37 UTC by redreceipt

2022-08-30 19:32 UTC, vinnyjth requested changes

2022-08-30 19:32 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
I don't think all items with children should have an up next button. 

For example - a list of resources doesn't need an up next button. I think the `upNextId` only is present on certain content item types (or interfaces)

2022-08-30 19:32 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +      variables={{ nodeId }}
yessss

2022-08-30 19:32 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +    return <Button style={styles.upNextButton(theme)} loading />;
love that we can remove so many of these abstractions

2022-08-30 19:32 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +                <Icon size={theme.sizing.baseUnit * 1.25} name={'check'} />
good simplification here 👍

2022-08-31 13:39 UTC, redreceipt commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
the problem is the server returns `upNextId=null` if the series is complete. that's why I took out the logic, it should show a disabled button. not a missing button.

2022-08-31 13:42 UTC, redreceipt commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
>    doneText,
gone

2022-08-31 13:44 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
that sounds reasonable to me - but I still don't think the solve is to show the button for every item, disregarding if it actually supports `upNext`

2022-08-31 13:47 UTC, redreceipt commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
what content item has children where it shouldn't show up?

2022-08-31 13:48 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
>For example - a list of resources doesn't need an up next button. I think the upNextId only is present on certain content item types (or interfaces)

2022-08-31 13:50 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
<img width="322" alt="CleanShot 2022-08-31 at 09 49 52@2x" src="https://user-images.githubusercontent.com/1637694/187694733-589cfe71-be07-412f-a8e8-83294e2f907b.png">

`ProgressNode` is a distinct interface that not all content items that implement `ChildContentItemsConnection` implement

2022-08-31 14:01 UTC, redreceipt commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
the up next button probably shouldn't be trying to retroactively make decisions on whether to show itself. this seems like a problem for one level up to solve.

2022-08-31 14:02 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
That was our approach for a while on these ContentNode connected components, we render them all and then they each decide if they should be show up. 

I'm more than happy if you have a different solve, but this does need to be solved :)

2022-08-31 14:14 UTC, vinnyjth commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
> the problem is the server returns upNextId=null if the series is complete. that's why I took out the logic, it should show a disabled button. not a missing button.

This situation should be okay though, right? Since this statement will return false since `childContentItemsConnection.length` will be > 0

2022-08-31 14:18 UTC, redreceipt commented on packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
> +        // The button is considered "supported" if it's a series that has children
I changed it to key off `percentageComplete` because what it returns is more straightforward.

2022-09-09 21:46 UTC, closed without merging