feat: BadgeListFeature
ApollosProject/apollos-apps pull request #2671
Opened 2022-09-21 12:50 UTC by vinnyjth

![2022-09-21 08 50 33](https://user-images.githubusercontent.com/1637694/191508302-b62c8df1-167f-47e5-8990-2ca0c6599b5f.gif)

2022-09-21 16:13 UTC, vinnyjth commented
![CleanShot 2022-09-21 at 12 12 51](https://user-images.githubusercontent.com/1637694/191556579-d980d43c-3b84-4398-9ece-79b78104cd6c.png)

Backported as well

2022-09-21 16:16 UTC, vinnyjth commented on templates/mobile/ios/Podfile.lock
> +  glog: 5337263514dd6f09803962437687240c5dc39aa4
```suggestion
  glog: 85ecdd10ee8d8ec362ef519a6a45ff9aa27b2e85
```

2022-09-21 16:16 UTC, vinnyjth commented on templates/mobile/ios/Podfile.lock
> +  RCT-Folly: a21c126816d8025b547704b777a2ba552f3d9fa9
```suggestion
  RCT-Folly: 803a9cfd78114b2ec0f140cfa6fa2a6bafb2d685
```

2022-09-21 18:32 UTC, calebpanza requested changes
So exciting to see this all in use! I could cry 😭

Test coverage is lower than I'd like. I'm really aiming for us to maintain 100% coverage on `ui-kit`. There's a new component that I have to work on (ButtonIcon) that could be ported into this, though, and that should raise coverage. So I won't let it block my review, but just dropping this as a note for later to remind ourselves to revisit test coverage.

2022-09-21 18:32 UTC, calebpanza commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.js
> +      opacity: contentOpacity.value,
Let's use `BodyText` here instead.

2022-09-21 18:32 UTC, calebpanza commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.js
> +      <SystemText color={active ? undefined : 'base.gray'}>{name}</SystemText>
`active ? 'text.primary` : 'text.tertiary` instead of `base.gray`.

and `align="center"`

2022-09-21 18:32 UTC, calebpanza commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.js
> +    <ScrollView horizontal>
Any particular reason for the ScrollView instead of a FlatList?

2022-09-21 18:32 UTC, calebpanza commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.styles.js
> +  borderRadius: unit(14),
Idk that this will make a perfect circle, actually.. Could set it to `999` just to be certain, but I _think_ it has to be at least the height/width. (or maybe half... I don't remember off the top of my head)

2022-09-21 18:35 UTC, vinnyjth commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.js
> +    <ScrollView horizontal>
Not really - I can refactor as a flat list.

2022-09-21 18:36 UTC, calebpanza commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.js
> +    <ScrollView horizontal>
That would be great! It should help resolve the key error, too

2022-09-21 18:36 UTC, vinnyjth commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.styles.js
> +  borderRadius: unit(14),
ah thanks. I had them all as `14`, but then I bumped the width/height and forgot to bump `borderRadius`

2022-09-21 18:37 UTC, vinnyjth commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.styles.js
> +  margin: unit(2),
👍

2022-09-22 14:05 UTC, calebpanza commented on templates/mobile/src/ui-kit/components/BadgeList/BadgeList.js
> +      opacity: contentOpacity.value,
Where do you see this component in Figma?

2022-09-22 14:16 UTC, calebpanza approved these changes
Looks good to me! I'm curious where the Figma main component is, though. I can't seem to find it inside of the UI Kit. If it's missing, I wanna make sure to create it in Figma, too.

2022-09-22 15:10 UTC, merged