fix: onboarding slides don't go missing anymore
ApollosProject/apollos-apps pull request #2687
Opened 2022-09-27 16:22 UTC by nlewis84

This PR addresses a bug where onboarding slides would go missing and the nav dots at the bottom would get weird on us.

https://user-images.githubusercontent.com/72768221/192581168-7d39693d-3cd0-4219-8415-4249cfd1416c.mp4

2022-09-27 16:27 UTC, vinnyjth commented on templates/mobile/src/onboarding/Onboarding/index.js
> +  if (slides.length === 0) {
there's a way to do this that might be a bit more "reacty" :) 

it's something like this 


```
const [slides, setSlides] = useState()
useEffect(() => {
   if (!slides.length && !loading) {
     // determine correct slides
   }
   setSlides(computedSlides)
}, [needsNameOnboarding, needsGenderBirthDateOnboarding, loading])
```

your current approach is great, but it runs the risk of blowing up if a new prop is ever passed into `Onboarding` Then this problem would occur again, because `slides` would be set again but this time with new data about the user. 

Explicitly tracking `slides` in `state` will make sure that it's only set once, after the data loads for the first time :)

2022-09-27 16:28 UTC, vinnyjth commented on templates/mobile/src/onboarding/Onboarding/index.js
> +    data?.currentUser?.profile?.gender === null ||
good catch :D

2022-09-27 16:35 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +  if (slides.length === 0) {
ooo I had something like this for a bit, but then I went the other direction.

2022-09-27 16:57 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +  if (slides.length === 0) {
I'm hitting some infinite looping due to needing to include slides in the dependency array for useEffect and it also getting set within the useEffect.

2022-09-27 16:59 UTC, vinnyjth commented on templates/mobile/src/onboarding/Onboarding/index.js
> +  if (slides.length === 0) {
ah that's fun. I think you can actually omit slides from the `useEffect` dependency array. This makes sense conceptually since you don't want the effect to respond to a change in `slides` :)

2022-09-27 17:18 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +  if (slides.length === 0) {
No luck with just omitting it. I'm trying to get clever with if statements inside the `useEffect` to avoid the loops.

2022-09-27 20:51 UTC, nlewis84 commented
@vincent here's the video of this new way of doing it working.

https://user-images.githubusercontent.com/72768221/192632753-a79dbcf6-73af-4d2c-af4d-ae6b02901244.mp4

2022-09-28 00:36 UTC, vinnyjth commented on templates/mobile/src/onboarding/Onboarding/index.js
> +        console.log(
Make sure to delete this comment.log :)

2022-09-28 00:37 UTC, vinnyjth commented on templates/mobile/src/onboarding/Onboarding/index.js
> +    const setSlidesFunction = async () => {
wow! funky! I'm assuming this does the hard work of isolating the useEffect dependencies? good find :)

2022-09-28 11:36 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +    const setSlidesFunction = async () => {
So data was flowing in async, and the useEffect fires off synchronously, so I needed to await data otherwise it would always think data was undefined, which meant you only ever got the 4 main slides.

2022-09-28 11:38 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +    const setSlidesFunction = async () => {
Oh, and I tried to use `slides.length` instead of `slides.length === 0` but for some reason that was not working. I wasn't sure what was up with that, but the more explicit version works so 🤷‍♂️

2022-09-28 11:39 UTC, nlewis84 commented
I think I may need to update some tests. Waiting for CI to pass.

2022-09-28 13:20 UTC, nlewis84 commented
@vinnyjth Are we still unconcerned by tests failing in the front end like a couple of months ago?

2022-09-28 13:37 UTC, nlewis84 commented on templates/mobile/ios/Podfile.lock
> +  glog: 5337263514dd6f09803962437687240c5dc39aa4
@vinnyjth These hashes changes when I ran yarn. Keep or ditch?

2022-09-28 13:37 UTC, nlewis84 commented on templates/mobile/ios/Podfile.lock
> +  RCT-Folly: a21c126816d8025b547704b777a2ba552f3d9fa9
@vinnyjth Same here. Keep or ditch?

2022-09-28 14:27 UTC, nlewis84 commented on templates/mobile/ios/Podfile.lock
> +  glog: 5337263514dd6f09803962437687240c5dc39aa4
it failed a test, so I backed this change out.

2022-09-28 14:28 UTC, nlewis84 commented on templates/mobile/ios/Podfile.lock
> +  RCT-Folly: a21c126816d8025b547704b777a2ba552f3d9fa9
it failed a test, so I backed this change out.

2022-09-28 15:18 UTC, vinnyjth commented on templates/mobile/ios/Podfile.lock
> +  RCT-Folly: a21c126816d8025b547704b777a2ba552f3d9fa9
yep! that's the right call :)

2022-09-28 16:06 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/__snapshots__/Onboarding.test.js.snap
> -exports[`the Onboarding component should render Onboarding 2`] = `
ummmm I've been trying 😅

2022-09-28 16:25 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/__snapshots__/Onboarding.test.js.snap
> -exports[`the Onboarding component should render Onboarding 2`] = `
I tried throwing `{ renderCount: 2}` on the test and also tried setting `<Onboarding slides={[jest.fn(), jest.fn(), jest.fn(), jest.fn()]} data={mockedCurrentUserObject} />`. I'm looking into maybe needing to mock the useEffect now. I don't see any examples of us having to do that elsewhere in the code base.

2022-09-28 21:01 UTC, vinnyjth approved these changes
works great, thanks!

2022-09-28 21:23 UTC, nlewis84 commented
I'll ping Michael tomorrow and see what his thoughts are on fixing the code coverage for this. Also, I don't know why tests are passing in the CI. They are not passing for me locally. 👀

2022-09-29 18:11 UTC, redreceipt requested changes
Snap should render

2022-09-29 18:24 UTC, nlewis84 commented
> Snap should render

@redreceipt Do you have any tips on adding test coverage for the code inside `useEffect`? Without adding a new package, I'm having trouble figuring it out.

2022-09-29 18:52 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +    return null;
@vinnyjth I did try `{ renderCount: 3 }` and it didn't work. I think this code is the issue, because I'm having trouble setting state in the testing environment and slides will always be `falsy`.

2022-09-30 04:10 UTC, conrad-vanl commented on templates/mobile/src/onboarding/Onboarding/index.js
> +  useEffect(() => {
look up the documentation for `useEffect` and its return value. Whenever you do something async inside of `useEffect`, you need to make sure that async work exits if it runs after the component un-renders.

In other words, if the component un-renders and `setSlides` is called, I think in React Native you'll get an RSOD cuz you're trying to set state on a component that doesn't exist. You might be able to do that as simple as:

```js
useEffect(() => {
  let active = true;
  
  const setSlidesFunction = async () => {
    if (!active) return;
    // ...
  }
  // ...
  
  return () => { active = false; }
}, []);
```

2022-09-30 04:13 UTC, conrad-vanl commented on templates/mobile/src/onboarding/Onboarding/index.js
> +    const setSlidesFunction = async () => {
Because you check for `slides.length` before data has been awaited?

2022-09-30 04:15 UTC, conrad-vanl commented on templates/mobile/src/onboarding/Onboarding/index.js
> +      if (slides.length === 0 && (await data)) {
Do you need the `slides.length` bit at all? With the way this `if` statement is structured, if `data` changes after it's initial value - then the slides won't be recomputed since this `if` is escaped if `slides` already has length.

So once `slides` has a length, no matter what happens to `data` the inside of this if statement never executes.

2022-09-30 04:16 UTC, conrad-vanl commented on templates/mobile/src/onboarding/Onboarding/index.js
> +      if (slides.length === 0 && (await data)) {
Also, I'm confused...how is `data` a promise? `data` is a promise?!

2022-09-30 04:23 UTC, conrad-vanl reviewed
I left some disparate comments.

Overall, I don't understand why we need `useEffect`. Is it so that we can keep `slides` from changing after they've been set? It feels like that's a smell and we're not getting at the real reason the data is changing.

With that said, if you wanted to only compute slides once and keep it from changing, `useMemo` might be a better way to do it. Have `useMemo` be based on `loading` perhaps.

```js
let computedSlides = [];
const slides = useMemo(() => {
   // logic for figuring out what `slides` is:
  if (!loading && !computedSlides.length) {
     const needsNameOnboarding =
     // and so on....
  }
  return computedSlides;
}, [loading]); // you might get some compiler warnings about dependencies...ignore 'em
```

Not sure if this would work, but I think it would.

2022-09-30 09:59 UTC, vinnyjth commented
> Overall, I don't understand why we need useEffect. Is it so that we can keep slides from changing after they've been set? It feels like that's a smell and we're not getting at the real reason the data is changing.

This is exactly why. The onboarding slides update because the slides change currentUser, so the Apollo hook is smart (and in this case, irritating enough) to rerender and drop slides.

2022-09-30 11:27 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +      if (slides.length === 0 && (await data)) {
You need slides.length, because the first time through, you need to `setSlides` or onboarding will get skipped entirely. Yep, `data` is a promise. The big issue that we are fighting is that once a user fills out the First/Last Name slide, `data` is updated, which means that they no longer need the first slide, so slides were recalculating and dropping the first slide, but then that made all sorts of wonky behavior happen with what index of the slides we were actually on and how many dots there were at the bottom of onboarding. Having it structured this way means that slides are only calculated one time, the first time this component is rendered, index of slides doesn't get messed up when a user completes info on the About You or Gender/Bday pages, and the nav dots don't get messed up.

2022-09-30 11:32 UTC, nlewis84 commented on templates/mobile/src/onboarding/Onboarding/index.js
> +  useEffect(() => {
Interesting! I'll add a cleanup function to this.

2022-09-30 11:37 UTC, nlewis84 commented
> With that said, if you wanted to only compute slides once and keep it from changing, `useMemo` might be a better way to do it. Have `useMemo` be based on `loading` perhaps.

I'll test out `useMemo` and report back. @vinnyjth is correct and I gave an in-depth answer in reply to one of your other comments @conrad-vanl

2022-09-30 12:45 UTC, conrad-vanl commented
So is the real thing that we simply want the query to stop running once we get our initial data set back? There is a `skip` option and we could be conditionally setting it, something like this stackoverlow answer: https://stackoverflow.com/a/60801406

I don't know if my `useMemo` advice above is right or any better, it could be worse. But simply just turning the query off, (by setting `skip=true`) after we've correctly constructed the slides array the first time might be the right solve.

> You need slides.length, because the first time through, you need to setSlides or onboarding will get skipped entirely.

I'm a little confused by this...are you saying that we're setting some value to slides initially so that onboarding doesn't get skipped? Should we just show a loading state or something else then?

2022-09-30 12:51 UTC, vinnyjth commented
@conrad-vanl Skip could work, but wouldn't we need `useState` for that? We would want to skip only after having fetched data once. Also I'm not sure how `skip` interacts with updates to a query unrelated to the original query call. In this instance - even if the `useQuery` doesn't refire directly, it's still getting new `data` because the internal cache is updating. I'm not sure if `skip` stops that propagation? 

`useMemo` sounds like a great route to me. @nlewis84 I have some time this morning to pair on it if you would like, we could try some cleanup and then see if we can get tests working.

2022-09-30 12:54 UTC, conrad-vanl commented
I'm thinking more about code cleanliness and clarity when someone goes back through and reads what's going on. having both `useMemo` and `skip` could be right as well..... right now it wasn't clear to me what we're trying to do here -> it looked like a code smell/mistake that we are preventing updating the component after we initially get data.

Ultimately turning the `userQuery` "off" feels like it's the most clear expression of what we want...

2022-09-30 12:56 UTC, vinnyjth commented
@conrad-vanl I've seen the pattern of `useEffect` / `useState` to capture data once and then avoid changing it more than once, I thought it was a accepted approach on how to do this :) 

in my mind the oddity is the use of await / inner-function

2022-09-30 12:56 UTC, conrad-vanl commented
We could also just use the `query` function instead of the hook - https://www.apollographql.com/docs/react/api/core/ApolloClient#ApolloClient.query

This would be async so we'd have to do it in a `useEffect` and `setState` ...

2022-09-30 12:58 UTC, vinnyjth commented
> Ultimately turning the userQuery "off" feels like it's the most clear expression of what we want...
> We could also just use the query function instead of the hook

These both feel strange to me - they make sense in component land, but they break down in stateless / functional land where a re-render could strike at anytime :) And the dependancy for how/when useQuery should be turned off is `useQuery` itself (which I think you address by mentioning  useEffect/setState)

2022-09-30 12:59 UTC, vinnyjth commented
I can see a version of this component that that uses `setState` for `slides` and determines slides based on `query` inside `useEffect` with no dependencies (so it only fires on mount). That makes sense to me.

2022-09-30 13:02 UTC, nlewis84 commented
@vinnyjth I'll ping you in a bit!

2022-09-30 13:04 UTC, conrad-vanl commented
> in my mind the oddity is the use of await / inner-function

Maybe it's just the variable naming or something to clean this up....

```js
const setUpSlidesOnlyOnce = useCallback(async () => {
  await data;
  // set up slides based on data
}, [data]); // not sure if we should have listed dependencies

useEffect(() => {
  setUpSlidesOnlyOnce();
}, []);
```

2022-09-30 14:53 UTC, vinnyjth commented
y'all, this PR has excellent tests and works great. I vouch for it 👍 💯

2022-09-30 14:57 UTC, redreceipt approved these changes

2022-09-30 17:08 UTC, merged