chore: adds church picker
ApollosProject/apollos-apps pull request #2695
Opened 2022-09-30 18:42 UTC by redreceipt

2022-09-30 18:42 UTC, redreceipt commented
dependent on github.com/apollosproject/apollos-cluster/pull/323

2022-09-30 19:53 UTC, calebpanza commented
Really cool idea! I'm excited to play around with this in TestFlight. 

What insurances are we gonna have, though, to make sure that this feature doesn't accidentally ship in one of our church apps?

With the UI Kit work that I'm doing, I introduced a new environment variable called `PROJECT_VARIANT`. Maybe we could expand on this so that our options are:

`storybook` - for rendering the Storybook app
`multitenant` or `demo` - for rendering the Apollos Demo app with the Church Picker
`church` or `client` - for rendering an app for a single church without the Church Picker

2022-09-30 20:33 UTC, redreceipt commented
if you define `CHURCH_HEADER` in the env, you can't pick a new one

2022-10-04 19:09 UTC, calebpanza commented
We talked about this in person, but I'm reiterating it here:
Instead of enabling a feature by _omission_ of a value, can we have the logic read `if CHURCH_HEADER=apollos_demo, enable the church picker`. That way we don't change the convention of requiring a value for CHURCH_HEADER, but instead we resolve the _functionality_ of the app based on the value of CHURCH_HEADER

2022-11-02 15:52 UTC, redreceipt commented
Ping for a review on this one

2022-12-01 21:12 UTC, vinnyjth requested changes
Crash on running with no `x-church` variables set 

```
 LOG  undefined {"errors": [{"extensions": [Object], "message": "Context creation failed: \"undefined\" not a valid church slug!"}]}
 WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property '__schema' of undefined
TypeError: Cannot read property '__schema' of undefined
    at _callee$ (http://localhost:8081/src/client/cache.bundle?platform=ios&modulesOnly=true&app=com.differential.apollos&dev=true&minify=false&runModule=true&shallow=true:149:51)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:23995:23)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:24165:32)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:24037:30)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:23995:23)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:24067:30)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:24077:21)
    at tryCallOne (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:30494:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:30390:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:30429:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:30639:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:3109:46)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:2887:45)
    at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:3092:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:2886:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.differential.apollos:2879:33)
```
    
<img width="658" alt="CleanShot 2022-12-01 at 16 11 32@2x" src="https://user-images.githubusercontent.com/1637694/205160032-885b7091-b018-4328-8370-0d3ff6c6fe47.png">

`.env.` file is empty.

2022-12-01 21:15 UTC, redreceipt commented
sweet, thanks for reviewing. not shocked it's broken. it's pretty old. I'll see what's up and get it fixed.

2022-12-01 21:25 UTC, redreceipt commented
Oh I see now, @calebpanza wanted to make sure this only makes into the demo app which I agree with, so I changed it to require the `CHURCH_HEADER` variable. But I think there are other ways we can lock that down. I really like that no `.env` is required for development. For now, we can base the picker off `process.env.NODE_ENV` like our other development tools and then figure out a way to deploy on the demo app in a follow up PR. The immediate need is easily being able to switch churches in development which this will solve.

2022-12-01 21:26 UTC, vinnyjth commented
Gotcha - so should I re-add my `church_header` env variable or are you going to add a workaround?

2022-12-01 21:26 UTC, vinnyjth commented
I honestly can't remember where we netted out on what belongs in the .env :)

2022-12-01 21:28 UTC, redreceipt commented
> I honestly can't remember where we netted out on what belongs in the .env :)

my point exactly. that's why it's better to not require it. I'm gonna post an update.

2022-12-01 22:13 UTC, calebpanza commented
@redreceipt @vinnyjth I still have every intention to run with this and apologize for the delay. I just haven't had time to come back to this with all the work on Daily Habits. Should be able to prioritize contributing to this by the EOY, though.

2022-12-06 20:29 UTC, redreceipt commented
@vinnyjth you shouldn't need an `.env` now

2022-12-06 20:34 UTC, vinnyjth commented on templates/mobile/src/settings/UserSettings.js
> +        {process.env.NODE_ENV === 'development' ? (
I like that this was `apollos_demo` because it made these changes super valuable for demoing the prod app with other churches data. Could the logic here be `NODE_ENV==dev or apollos_demo`?

2022-12-06 20:37 UTC, redreceipt commented on templates/mobile/src/settings/UserSettings.js
> +        {process.env.NODE_ENV === 'development' ? (
done. good call. that takes care of all concerns.

2022-12-06 20:47 UTC, vinnyjth submitted a review, later dismissed
Incredible to see this in motion. 

Approving with two notes: 

1. Nothing user/campus related seems to work. That's not unexpected. And you seem to get booted back to `apollos_demo` if you try to change your campus. 
2. You get an error if you select a church without a theme (like `fake`) 
![CleanShot 2022-12-06 at 15 47 33@2x](https://user-images.githubusercontent.com/1637694/206019621-6252cf0f-f631-49a5-a309-1195e6a14a5e.png)

2022-12-06 20:50 UTC, redreceipt commented
that's no good. I'd like to fix before merging. the second is easy. the first I'll need to dig in. can you give me an example to work through?

2022-12-06 20:52 UTC, vinnyjth commented
@redreceipt A good example is to try and change your campus. 

I expect this to be a big challenge because the currently logged in user isn't valid in whatever church slug you end up selecting. Your best path is probably to log the user out immediately upon switching churches.

2022-12-06 20:53 UTC, vinnyjth commented
I approved because this has huge value today, even with the oddities. I'm fine if you focus on fixing the first issue in a follow up PR.

2022-12-06 21:43 UTC, vinnyjth commented
Really close! 

1. Login to the app.
2. Select "Woodmen Valley" 
3. Login to the app again
4. Visit the "Profile" screen and try and change your campus
5. The app kicks you back out to login and you are back in Apollos Demo
- The "selector" is defaulted to Apollos Demo, I wonder if it's "on select" is firing or if it's somehow changing the state.

2022-12-06 22:11 UTC, redreceipt commented
doesn't seem to be the campus call, that one comes back fine with the correct headers, must be something else

<img width="1142" alt="Screenshot 2022-12-06 at 5 10 05 PM" src="https://user-images.githubusercontent.com/2659478/206034409-f53a4ba7-cef5-44f9-96d7-cd2689a65405.png">

2022-12-06 22:15 UTC, vinnyjth commented
@redreceipt I think it's more likely the Connect screen is rerendering or something when you open the Campus selector, triggering the state of the the church to be reset to 0 (or something)

2022-12-06 22:40 UTC, vinnyjth commented
@redreceipt maybe because it's a navigation action? The MapView being inside a Navigator modal?

2022-12-06 22:41 UTC, redreceipt commented
something like that. I'm investigating. hard to believe that would cause the whole app to re-render

2022-12-06 22:50 UTC, redreceipt commented
verified it doesn't happen in master so something is triggering a full re-render of the whole app, just not sure what

2022-12-06 23:16 UTC, redreceipt commented
figured it out. seems to be a UI crash with the `Picker` from `react-native-picker`. commented out and the map view shows up fine. with it, even without using, the whole app re-renders.

2022-12-06 23:19 UTC, redreceipt commented
gonna upgrade the package, we're a major version behind

2022-12-06 23:50 UTC, redreceipt commented
upgrading versions didn't help. we may to consider a different UI.

2022-12-07 00:04 UTC, redreceipt commented
I'm gonna try and fix systematically:
- upgrade picker
- (if that doesn't work) upgrade maps pkg
- (if that doesn't work) remove picker from our repo and figure out another UI for this PR

2022-12-07 00:27 UTC, redreceipt commented
> I'm gonna try and fix systematically:
> 
> * upgrade picker
> * (if that doesn't work) upgrade maps pkg
> * (if that doesn't work) remove picker from our repo and figure out another UI for this PR

this theory didn't prove out on master so now I'm confused

2022-12-07 01:23 UTC, redreceipt commented
@vinnyjth got it. even fixed the theme colors. icons and word marks aren't working but I think we should pull those as URLs and pass them through the theme too. I can do that in another PR. I dismissed your review so you could retest with the changes.

2022-12-07 02:02 UTC, vinnyjth approved these changes
Looking great! Nice work. The button at the bottom of the picker was a good UI solve.

2022-12-07 02:02 UTC, merged