fix: auth enhancements
ApollosProject/apollos-apps pull request #2709
Opened 2022-10-16 00:10 UTC by redreceipt

- easier to tap log in button
- forced openID if available
- cant skip openID
- auto loads openID
- removes webview

2022-10-17 13:00 UTC, conrad-vanl commented
<img width="294" alt="Screen Shot 2022-10-17 at 7 59 51 AM" src="https://user-images.githubusercontent.com/103927/196183413-f4dcf42d-4dc4-4185-a3dc-5fbf94ecab83.png">

WDYT about replacing this screen with just a centered `<ActivityIndicator/>` and then if the openid flow gets exited or error'd we can display a simple error message with a link/button to open OpenID again?

2022-10-17 13:01 UTC, conrad-vanl commented on templates/mobile/src/auth/LandingSwiper/slides.js
> +              <ButtonLink onPress={onPress}>Log in →</ButtonLink>
I don't think the hit area on this is going to be any bigger then it was before, the padding is added outside of the link. I think you need to either add padding directly to `ButtonLink` or use `hitSlop`

2022-10-17 18:02 UTC, redreceipt commented
@conrad-vanl done, done, and done

2022-10-17 18:03 UTC, redreceipt commented
I think I need a lesson on hitslop. adding it does nothing.

2022-10-24 16:16 UTC, conrad-vanl commented
> I think I need a lesson on hitslop. adding it does nothing. padding worked though.

Yeah, you may not be able to notice any difference unless you're testing on a real device.

Can you provide an updated screenshot with the padding implementation?

2022-10-24 17:34 UTC, redreceipt commented
> Can you provide an updated screenshot with the padding implementation?

cc @conrad-vanl you can't really tell from the video but I'm clicking below, to the right, and above the button


https://user-images.githubusercontent.com/2659478/197589593-06f3f77f-642f-45b2-a7ca-7fe79f9e8c7c.mp4

2022-10-27 13:11 UTC, vinnyjth requested changes
Sorry it's taken me so long to review this 😅 

We're showing the "Would you like to use the church_name .... " prompt on top of the first onboarding screen. Clicking confirm opens up the webview. We should see if we can avoid showing this prompt if you've already completed the flow.

![2022-10-27 09 09 09](https://user-images.githubusercontent.com/1637694/198293315-55173127-9ee8-4e36-ba8d-644647c911b1.gif)

2022-10-27 13:11 UTC, vinnyjth commented
Maybe helpful for debugging - I see three of these warnings: 
![CleanShot 2022-10-27 at 09 11 32@2x](https://user-images.githubusercontent.com/1637694/198293753-77580bc1-fbb3-42c9-aca2-56766c6c294b.png)

2022-10-29 02:28 UTC, redreceipt commented
ok @vinnyjth this is ready for another review. it ballooned much more than I originally intended on my most recent commit but I think I took care of the issue you found as well as some other small auth bugs. Most notably, I removed the `AuthContext` provider and just made the login/logout functions direct utility imports. It was causing subtle re-render bugs every time we set a new login status. Plus they don't need to be in the context anyway. I would appreciate a glance over all the code one more time as well as some light sim testing over various auth functions.

2022-10-31 11:11 UTC, vinnyjth commented
@redreceipt I like the cleanup you were able to achieve, but token refresh no longer works :/ 

![2022-10-31 07 10 21](https://user-images.githubusercontent.com/1637694/198995007-07969df9-5f1e-449c-a63d-ef4e7b0ad8c6.gif)

2022-10-31 11:15 UTC, vinnyjth commented
Nevermind - same issue happens in master I think ... that worries me a bit. I'm trying to make sure token expiration is working as expected

2022-10-31 11:33 UTC, vinnyjth approved these changes

2022-10-31 14:47 UTC, vinnyjth commented on templates/mobile/src/auth/LandingSwiper/index.js
> +    // const defaultAuthScreen = data?.openIdProviders?.length
```suggestion
    const defaultAuthScreen = data?.openIdProviders?.length
```

2022-10-31 14:47 UTC, vinnyjth commented on templates/mobile/src/auth/LandingSwiper/index.js
> +      // ? 'Auth'
```suggestion
      ? 'Auth'
```

2022-10-31 14:47 UTC, vinnyjth commented on templates/mobile/src/auth/LandingSwiper/index.js
> +      // : 'IdentityEntryConnected';
```suggestion
      : 'IdentityEntryConnected';
```

2022-10-31 14:59 UTC, redreceipt commented on templates/mobile/src/auth/LandingSwiper/index.js
> +      const defaultAuthScreen = 'IdentityEntryConnected';
```suggestion
```

2022-10-31 19:36 UTC, vinnyjth commented
@redreceipt can you resolve conflicts for me? thanks :D

2022-11-01 12:40 UTC, vinnyjth commented
<img width="1577" alt="CleanShot 2022-11-01 at 08 40 15@2x" src="https://user-images.githubusercontent.com/1637694/199234561-8df3ca36-4108-4871-a21c-f7347c9c5b54.png">

🤔  is this a legit failure?

2022-11-01 19:54 UTC, vinnyjth commented
My fix didn't work @redreceipt :(

2022-11-01 19:59 UTC, redreceipt commented
yea I'm looking into it now. must be something else.

2022-11-01 20:37 UTC, redreceipt commented
I think I got. The method I was using to identify the component was flaky (there was a missing trailing space at the end of the text) so I moved it to use `testID`.

2022-11-01 22:52 UTC, merged