chore: move content and features to templates
ApollosProject/apollos-apps pull request #2744
Opened 2022-10-28 15:27 UTC by redreceipt

this will allow us to migrate a couple of the pkgs that were cross-dependent from `ui-connected`

2022-11-01 14:07 UTC, calebpanza requested changes
![CleanShot 2022-11-01 at 10 07 30](https://user-images.githubusercontent.com/45076058/199252824-234609a1-1dcb-4cd4-9061-4f2824e83d5d.png)

2022-11-01 15:49 UTC, redreceipt commented
@calebpanza I just pulled this branch and booted again no problem, how did you get to see this error? did you nav somewhere in the app?

<img width="1402" alt="Screenshot 2022-11-01 at 11 48 50 AM" src="https://user-images.githubusercontent.com/2659478/199276782-722b8775-ddb7-4c7a-b287-4b93118acd15.png">

2022-11-01 16:22 UTC, redreceipt commented
> @redreceipt all I ended up doing was `yarn && yarn start`. I'll try it again

did you yarn in the root as well? symlinked pkgs are now different as well

2022-11-01 16:25 UTC, calebpanza commented
@redreceipt looks like there was a missing import on the `createTab`. I bet that the `ui-connected` package was cached on your local machine or something

2022-11-01 16:40 UTC, redreceipt commented
> @redreceipt looks like there was a missing import on the `createTab`. I bet that the `ui-connected` package was cached on your local machine or something

boom, I bet you're right. Thank you!

2022-11-01 20:10 UTC, calebpanza approved these changes

2022-11-01 23:59 UTC, redreceipt commented on templates/mobile/__mocks__/@apollosproject/ui-kit.js
> +export const CenteredView = 'CenteredView';
```suggestion
export const CenteredView = 'CenteredView';

```

2022-11-02 11:23 UTC, vinnyjth approved these changes

2022-11-02 11:23 UTC, vinnyjth commented
Love it! thanks man

2022-11-02 11:42 UTC, redreceipt commented
Not sure why the test is failing here. Might involve some tricky GitHub actions debug.

2022-11-02 13:51 UTC, redreceipt commented
test only fails on linux, jest is failing with an exit code of 1 but passing all tests...
<img width="382" alt="Screenshot 2022-11-02 at 9 50 43 AM" src="https://user-images.githubusercontent.com/2659478/199506910-5736d0f4-259f-4882-9ac9-fba1f423213a.png">

2022-11-02 14:09 UTC, redreceipt commented
it's badgelist and something with reanimated

<img width="382" alt="Screenshot 2022-11-02 at 9 50 43 AM" src="https://user-images.githubusercontent.com/2659478/199510941-7e5fc7e0-f909-4fe4-8d2b-239be4625652.png">

2022-11-02 14:15 UTC, redreceipt commented
got it. animated stuff needs fake timers

2022-11-02 15:49 UTC, redreceipt commented on .github/workflows/ci.yml
> +        uses: mxschmitt/action-tmate@v3
```suggestion
```

2022-11-02 18:26 UTC, merged