Create topics onboarding page
ApollosProject/apollos-apps pull request #2799
Opened 2022-11-21 19:43 UTC by jackcrane

First round for review, will elaborate later

2022-11-22 05:48 UTC, jackcrane commented
After a very productive huddle with @calebpanza we reorganized the code to better match Apollos conventions and to utilize the `ui-kit`. This is still using dummy data in `templates/mobile/src/onboarding/slides/TagGroups/TagGroupsConnected.js` and has no reactivity or webcode yet, but progress nonetheless! Attached is a screenshot of the current state.

<img width="485" alt="Screen Shot 2022-11-21 at 11 45 54 PM" src="https://user-images.githubusercontent.com/45675751/203234483-4205e26d-fa46-4f4e-aafc-8d506dc8f1f0.png">

2022-11-22 17:58 UTC, calebpanza commented
🙌🙌🙌

2022-11-23 21:53 UTC, jackcrane commented
In [810971e](https://github.com/ApollosProject/apollos-apps/pull/2799/commits/810971e7277b482981512489acb4a00461e85f3d) I pulled the `TagContainer` that holds the `PressableChip` into its own component so it can manage its own state and make requests to the API on selection/deselection. The API is not completely caught up so I cannot completely test the integration but the bones are here :). I also set up a bunch of test data in the staging db (`tag_group_tags`)

<img width="485" alt="Screen Shot 2022-11-23 at 4 53 04 PM" src="https://user-images.githubusercontent.com/45675751/203652276-1fbe1c8c-5d9c-4168-a569-8f1b80d6e0ce.png">

2022-12-21 18:52 UTC, jackcrane commented
Finalizing the feature addition. Final commits caught the UI up to master and incorporated error handling. UI Appearance has not changed since the screenshot above, and attached is a screen recording of network failure behavior.

https://user-images.githubusercontent.com/45675751/208980704-7d6cfa33-6c43-470d-803f-4adc1e194589.mov

2023-01-03 16:31 UTC, calebpanza requested changes

2023-01-03 16:31 UTC, calebpanza commented on templates/mobile/src/components/TagGroup/TagGroup.js
> +const Tag = ({ tag, i }) => {
Could you break out these components into their own files? Will make it easier to run tests later on and easier to track down the location.

2023-01-06 16:32 UTC, jackcrane commented
I have added all the tests I can think to do, have tested the functionality as much as I reasonably can. I will continue brainstorming ideas to better test the components and improve coverage. 

The naming is slightly confusing with singular and plural `TagGroup` and `TagGroups`, so below is a hierarchy

```javascript
<TagGroups> // covered by TagGroups.test.js
  <TagGroup> // covered by TagGroup.test.js
    <Tag /> // covered by Tag.test.js
    /* ... any number of Tag components ... */
  </TagGroup>
  /* ... any number of TagGroup components ... */
</TagGroups>
```

<img width="564" alt="Screen Shot 2023-01-06 at 11 26 44 AM" src="https://user-images.githubusercontent.com/45675751/211054512-a2a19ea1-698f-46e4-83b0-0fa92a815a13.png">

I would appreciate some input on additional tests to add to the suite, especially on `TagGroup.js`, covered by `TagGroup.test.js`.

2023-01-13 16:44 UTC, dsilva609 requested changes

2023-01-13 16:44 UTC, dsilva609 commented on templates/mobile/src/components/TagGroup/TagGroup.js
> +  title: 'hgdf',
Should this title just be an empty string for default?

2023-01-13 16:44 UTC, dsilva609 commented on templates/mobile/src/onboarding/slides/TagGroups/index.js
> +// export FollowConnected from './FollowConnected';
is this needed?

2023-01-13 16:50 UTC, jackcrane commented on templates/mobile/src/components/TagGroup/TagGroup.js
> +  title: 'hgdf',
Yes, will fix

2023-01-17 17:40 UTC, calebpanza requested changes
![CleanShot 2023-01-17 at 12 38 31](https://user-images.githubusercontent.com/45076058/212972139-373477a0-db4e-4684-bbad-8d1758a590f7.png)

Default behavior when there is _no_ tag groups coming from the server should be to remove this screen from onboarding.

2023-01-17 18:09 UTC, calebpanza commented
@jackcrane looks like there is a missing import on the `useTagSelected` hook.

![CleanShot 2023-01-17 at 13 07 16](https://user-images.githubusercontent.com/45076058/212977691-b11e3073-9121-4c27-a605-b8670fbeaa8b.png)

For that hook, could you make sure to have that mutation localized inside of `useTagGroup` and not to have `SELECT_TAG` be imported?

Could we also move that hook into the `utils` directory? (I plan to rename that directory to `hooks` during cooldown)

Lastly, let's get some level of test coverage on that hook in order to avoid any future misgivings.

2023-01-17 18:30 UTC, dsilva609 commented on templates/mobile/src/components/TagGroup/useTagSelected.js
> +  const selectTag = (tagId) => {
Just a small thing on the naming on this variable. Seeing `select` here makes it seem like what's being done is a query. Would changing it to something like `updateTagSelection` convey the same meaning while also sounding more like a mutation is happening?

2023-01-17 18:30 UTC, dsilva609 commented on templates/mobile/src/onboarding/slides/TagGroups/selectTag.js
> +    selectTag(tagId: $tagId) {
Echoing the comment from above, but could this be renamed to something like `updateTagSelection`?

2023-01-17 18:56 UTC, calebpanza commented on templates/mobile/src/components/TagGroup/useTagSelected.js
> +  const selectTag = (tagId) => {
or rather `useUpdateTagSelection` to follow in proper hook naming standards

2023-01-20 16:50 UTC, calebpanza commented
@jackcrane do you need help getting this landed? I can make some time to dive into this if you need some help. Would really like to get this landed in the next few days

2023-01-20 16:52 UTC, jackcrane commented
i should be able to get it there over the weekend. right now all that is left is to add tests for the hook. 

as of now i cannot get the app to launch in sim on my mac which has held some of my progress up.

2023-01-21 00:31 UTC, jackcrane commented
Feature _should_ be finished, just awaiting review `:)`

2023-01-23 14:14 UTC, dsilva609 commented on templates/mobile/src/onboarding/slides/TagGroups/index.js
> +// export FollowConnected from './FollowConnected';
@jackcrane is this export still needed?

2023-01-23 16:17 UTC, dsilva609 commented
fixed a bad import and gave it a test and it's looking good 👍

2023-01-23 16:20 UTC, dsilva609 approved these changes

2023-01-27 19:09 UTC, camrun91 commented
@vinnyjth looks like this is waiting on @calebpanza to approve the changes it looks like they are good to go though. Do we want to force merge?

2023-01-27 19:23 UTC, vinnyjth commented
@camrun91 I think we need to hold off on this one - we need to make sure it isn't going to show up unless there are tag groups configured. 

Can we update this PR to remove https://github.com/ApollosProject/apollos-apps/pull/2799/files#diff-d6323377510f7dd23611f7fee6055176da929eca9164e25e890cfe4633b5e937R68 these lines - so the screen doesn't show up at all, then do a follow up PR that actually adds this screen to onboarding _if_ there are tag groups?

2023-01-27 19:25 UTC, camrun91 commented
Ah I got it I didnt think about there not being tag groups.

2023-01-27 19:28 UTC, jackcrane commented
Im not able to test it because the app is not launching for me (have been fighting dependencies). The entire feature returns null when there are no tags returned by the API, which should (in theory) not display the page at all and allow onboarding to flow naturally

2023-01-27 19:30 UTC, vinnyjth commented
> The entire feature returns null when there are no tags returned by the API, which should (in theory) not display the page at all and allow onboarding to flow naturally

💥 

In that case @cameron - can you test the above logic to confirm and then merge? 

There's now a tag group editor in retool

2023-01-30 03:32 UTC, jackcrane commented
After finally getting the app to work and testing, my logic did not, in fact, work. Working on a fix.

2023-01-30 14:06 UTC, jackcrane commented
Functionality is there, need to write tests.

2023-01-30 18:26 UTC, dsilva609 commented
> Functionality is there, need to write tests.

@jackcrane pushed a small fix for an incorrect variable, but otherwise everything checks out 👍

2023-01-30 22:14 UTC, vinnyjth commented
@camrun91 can you share the error you are seeing?

2023-01-30 22:18 UTC, camrun91 commented
<img width="1428" alt="Screenshot 2023-01-30 at 4 18 04 PM" src="https://user-images.githubusercontent.com/16566029/215608439-35b241c9-97e7-4c4b-b5b7-fbf725183326.png">
@vinnyjth

2023-01-31 14:51 UTC, dsilva609 commented
> @dsilva609 @calebpanza after uninstalling the app and trying to reinstall to sim from this branch I can not get it to install at all it looks like some of the project files changed in this PR. I dk if those are causing issues or not.

I'm seeing the same too now. Tried cleaning and rebuilding in xcode and it didn't help. Won't even launch now.
@jackcrane are you still able to get it to launch?

2023-01-31 15:06 UTC, dsilva609 commented
@camrun91 are you able to get it to launch by using the previous version of the updated `.pbxproj` file?

2023-01-31 15:09 UTC, dsilva609 commented on templates/mobile/ios/apolloschurchapp.xcodeproj/project.pbxproj
> +		6ABB80E329872BF5002D3938 /* NotificationService.swift in Sources */ = {isa = PBXBuildFile; fileRef = BF49AE862649A852001C7B78 /* NotificationService.swift */; };
@jackcrane These updates seem to be causing the install to fail

2023-01-31 17:11 UTC, camrun91 commented
@dsilva609 yes matching the one that is in master fixes it. I am now trying to get the screen to show up.

2023-01-31 17:24 UTC, camrun91 commented on templates/mobile/ios/apolloschurchapp.xcodeproj/project.pbxproj
> +		6ABB80E329872BF5002D3938 /* NotificationService.swift in Sources */ = {isa = PBXBuildFile; fileRef = BF49AE862649A852001C7B78 /* NotificationService.swift */; };
@jackcrane @dsilva609 I just pushed changes that fix this. Jack if this is something that is needed for somereason please let us know.

2023-01-31 18:03 UTC, camrun91 commented
I can not get this to show up for some reason.

2023-01-31 20:34 UTC, camrun91 commented
OK I finally got this to work. I had to do some logging and it finally showed up when the sim reloaded in the middle of onboarding. I would love for someone else to validate that this works with out having to trouble shoot.

2023-01-31 23:37 UTC, jackcrane commented
Those seem to have been leftovers from me attempting to get the app to launch. They can be reverted fine :)

2023-02-01 18:24 UTC, calebpanza commented
@jackcrane could you also revert the addition of the `IDECheck` file? The rest of this is looking good to me

2023-02-01 20:01 UTC, jackcrane commented
I will delete the extraneous file and re-test everything 👍

2023-02-01 20:37 UTC, merged