Chore: Analytics refactor
ApollosProject/apollos-apps pull request #2808
Opened 2022-11-23 05:54 UTC by conrad-vanl

## ✏️ Description

Significantly refactors/simplifies the ui-analytics package and implements built-in support for a global Segment setup.

### Backstory
In evaluating our data needs, I've learned that:

- We need to track much better data for our own purposes. We have no cross-church analytics and no way to look at app performance in the micro
- This not only makes product decisions harder, but leaves all of our teams (marketing, sales, customer success, etc) without access to valuable shared data
- Furthermore, many of our clients are starting to desire more data sent to more platforms: Tableau, GA, Rock, etc. Setting up additional data destinations is difficult with our current setup
- Something like Astronomer is not optimized for click-stream data (although it works great in a reverse ETL setup like we have it now)
Also, `identify` is never being called on production, so amplitude or anything is not getting that information.

### Customer Data Platform
I am still evaluating Customer Data Platform solutions. Segment, mParticle, Rudderstack, Salesforce, etc. Segment appears to be a clear choice for now:

- Price model nets it out cheaper then some competitors with lots of room to grow
- High number of integrations
- Ability to programmatic control destinations and filtering per-destination, meaning we could use Segment to funnel customer-specific data to customer-specific tools (such as use Segment to funnel Rock data for a single church into their Rock)

### This removes our server-side analytics tracking
So far, this PR removes tracking to our server-side analytics. I'm not even sure if any church is using this outside of Crossroads (which, unfortunately, they use Segment....and the greatest drawback of Segment is they don't seem to have a Segment to Segment solution). However, these track events are accounting for a reasonable amount of our web traffic on the API, so removing these hits to our API might improve performance overall.

### I made the TV Changes blind
I tested mobile, but I have not booted TV to see if these changes work without error. I believe they should, but will need more 👀 on this.

## 🔬 To Test
1. Add Segment key to your .env: `SEGMENT_KEY=rwkfWr0HpIW4eSUZqI30BmcMAdwsVrW0` (I don't anticipate using this key in production)
2. Boot up the sim, click around
3. Login to Segment and check [the live event stream](https://app.segment.com/differential-conrad/sources/apollos/debugger) (password in 1password)

## 📸 Screenshots

<img width="611" alt="Screenshot 2022-11-22 at 11 50 12 PM" src="https://user-images.githubusercontent.com/103927/203480254-658c4da3-b7db-498c-8fe7-cb779c3688a2.png">

## ⚠️ To-do Before Merge

- [ ] Test that amplitude and onesignal events are still coming through correctly
- [ ] Confirm we don't need the apollos-cluster server-side tracking events
- [ ] Decide that routing everything to a CDP is the right solution
- [ ] Test that TV is actually working!

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

2022-11-23 05:57 UTC, conrad-vanl commented
@vinnyjth / @jordanwade / @redreceipt not going to mark this ready for review, but this is something I've talked to @vinnyjth some about and I think it's to a point where I'd like y'alls feedback on:

- How I'm keeping ui-analytics and sharing between mobile and tv
- That I'm removing server-side tracking
- Other ideas before I continue investigating CDP options
- Anything else? should I remove some of the backward compatibilities and touch more code?

Also, this is nice. Most of the deletions are from snapshots but it is removing a lot of low-value code:
<img width="156" alt="Screenshot 2022-11-22 at 11 57 27 PM" src="https://user-images.githubusercontent.com/103927/203480908-969e1fcc-6ae0-4d5a-bb62-0d77d4bd619b.png">

2022-11-23 06:00 UTC, conrad-vanl commented
PS...the main component/file to look at is `packages/apollos-ui-analytics/src/Provider.js`. All other changes were made to support that file. That's the new "Core" analytics provider that this PR proposes we use on react-native based projects.

2022-12-06 19:56 UTC, jordanwade commented
@conrad-vanl I tried to test this out on TV. There are a few simple import issues. But, the biggest problem is the `apollos-config` requires AsyncStorage. If I remember correctly, TVs can't rely on that since cache is blown away regularly and it has a pretty strict limit on its size. Instead, in the TV app we use a package called `react-native-default-preference` to act as a local storage for things like auth tokens.

Do you have any ideas on how to work around that dependence?

2022-12-06 20:05 UTC, vinnyjth commented
@jordanwade @redreceipt has a PR that gets rid of `ApollosConfig` :) 

I'm not sure if that also removes the AsyncStorage dependency also.

2022-12-06 20:06 UTC, redreceipt commented
it doesn't touch asyncstorage

2023-01-14 19:48 UTC, conrad-vanl commented
@vinnyjth I put Core Interactions (our graphql interactions) back into this package. Instead of relying on our dated code, I was able to leverage @jordanwade's version that they had in TV.

I tested that it works by completing the "Read Scripture" step of the daily reading.

Going to test up on TV then this _might_ be ready for merge.

2023-01-15 02:55 UTC, conrad-vanl commented
Had to rip out Segment on TV as it appears `segment-react-native` doesn't work on atleast tvOS. 

That's ok, once we validate segment's long term feasibility we can utilize Segment's JS library on the tv side.

2023-01-20 14:28 UTC, calebpanza commented
@conrad-vanl catching up on this PR. Is the intention for this to be additive so we can run both packages (Amplitude and Segment) alongside each other?

2023-01-20 14:43 UTC, conrad-vanl commented
@calebpanza yes, this PR is meant to maintain backwards compatible support for current clients that use Amplitude (same with OneSignal). 

Going forward, we'll likely use Segment to forward events to clients' Amplitude apps, but this can be launched without breaking anything for existing clients.

2023-01-20 14:47 UTC, conrad-vanl commented
@calebpanza i also just invited you to segment so you can test events flowing in locally.

Just set your segment key env var (look at the code to see what it should be 😉  )

The source event debugger sometimes has a delay (I thought it wasn't working for a while then POOF events started flowing in -> https://app.segment.com/apollos/sources/apollos/debugger )

2023-01-20 15:50 UTC, calebpanza requested changes
Sorry for the lengthy review! 😅 It's a _lot_ of pretty substantial changes and just wanna make sure it's all tidy. Excited for the updates and looking forward to gathering more data.

I'm more than happy to jump in and help resolve any of the changes here. @conrad-vanl let me know if you'd like for me to jump into any of these things.

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-tv-shared/providers/AppProvider.js
> +      <AnalyticsProvider>
Same question about whether the addition on TV is valid given the issues with TV & Segment

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/package.json
> -    "@apollo/client": "3.6.9",
What this intentional? On the `CoreInteractions.js`, you're importing from `@apollo/client`

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/CoreInteractions.js
> +export const useCoreTrack = (options = {}) => {
📝 great chance to add some documentation

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/CoreInteractions.js
> +export const useCoreIdentify = (options = {}) => {
📝 great chance to add some documentation

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +  clients = defaultClients,
Just a random question. Is there any difference in using inline defaults vs. AnalyticsProvider.defaultProps?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      screen: (...args) =>
📝 great chance to add some documentation

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      track: (eventName, properties, ...args) => {
📝 great chance to add some documentation

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      identify: (...args) =>
📝 great chance to add some documentation. Are these segment-specific?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      flush: (...args) =>
📝 great chance to add some documentation. Are these segment-specific?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      group: (...args) =>
📝 great chance to add some documentation. Are these segment-specific?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      alias: (...args) =>
📝 great chance to add some documentation. Are these segment-specific?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      reset: (...args) =>
📝 great chance to add some documentation. Are these segment-specific?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +      return;
Should this return or does it need to clear the current identity?

Example:

- I log in --> Identity === Caleb
- I log out --> Identity === Caleb
- I log in as Conrad but something fails in the network request --> Identity === Caleb

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +  useEffect(() => {
The use of a separate effect seems a bit redundant and this effect could be captured in the comment above on line `108`. Save from another effect firing off

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.tests.js
> +describe('Provider', () => {
Tests are freaking out on my local machine. Says it'll take over 7 minutes to run 11 tests and this error keeps popping up

```  
●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Warning: An update to AnalyticsProvider inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in AnalyticsProvider (created by ProviderStack)
        in ApolloProvider (created by MockedProvider)
        in MockedProvider (created by ProviderStack)
        in ProviderStack".

      at console.error (../../node_modules/@jest/console/build/BufferedConsole.js:165:10)
      at printWarning (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:110:34)
      at error (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:88:9)
      at warnIfNotCurrentlyActingUpdatesInDEV (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11524:11)
      at dispatchAction (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5599:13)
      at ../../node_modules/@apollo/client/react/hooks/useMutation.js:76:21
      at tryCallOne (../../node_modules/react-native/node_modules/promise/lib/core.js:21:12)
      at ../../node_modules/react-native/node_modules/promise/lib/core.js:122:15
      at flush (../../node_modules/asap/raw.js:25:25)
```

Coverage also seems a bit low. Would love to help get coverage a bit higher due to the significance of the code.

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
>      expect(tree).toMatchSnapshot();
What is the snapshot proving in this situation? The test wants to confirm that the `trackEvenName` is being passed through properly, but the snapshot gives no indication that's the case. A better test might be to run the `onPress` on the button and confirm the proper event name is being passed through

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
>      expect(tree).toMatchSnapshot();
Same comment as above

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
>      expect(tree).toMatchSnapshot();
Same comment as above

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-connected/src/DailyHabitsConnected/PrayerExperience/PrayerSwipeScreen.js
> +  const track = useTrack();
One of the comments in the code mentioned to prefer using the `useAnalytics` hook over the `useTrack`. Is this a case where we should update this section to use the new method?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-prayer/src/PrayerExperienceConnected/index.js
> +  const track = useTrack();
Same question as above. Should this be updated to `useAnalytics`?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-prayer/src/screens/AddPrayerScreenConnected/index.js
> +  const track = useTrack();
Same question as above. Should this be `useAnalytics`?

2023-01-20 15:50 UTC, calebpanza commented on packages/apollos-ui-prayer/src/screens/PrayerScreen/index.js
> +  const track = useTrack();
Same comment as above. Should this be `useAnalytics`?

2023-01-20 15:50 UTC, calebpanza commented on templates/mobile/src/components/PrayerExperienceSwiper/PrayerExperienceSwiper.js
> +import { useTrack } from '@apollosproject/ui-analytics';
Is this suppose to be `useAnalytics`?

2023-01-20 15:50 UTC, calebpanza commented on templates/mobile/src/analytics/segment.js
> +    writeKey: Config.SEGMENT_KEY || 'rwkfWr0HpIW4eSUZqI30BmcMAdwsVrW0',
Probably shouldn't use a default value here. If no key is set, should probably just report to Sentry and crash the app or something

2023-01-20 20:10 UTC, conrad-vanl commented
<img width="54" alt="Screenshot 2023-01-20 at 2 10 04 PM" src="https://user-images.githubusercontent.com/103927/213796629-6a376e88-9f83-4416-925c-94a2db442b24.png">
This escalated quickly. Thanks for the thoroughness! I'll dig in

2023-01-20 20:11 UTC, conrad-vanl commented on packages/apollos-tv-shared/hooks/useAnalytics.js
> +export { useTrack, useIdentify } from '@apollosproject/ui-analytics';
No, I don't think so, because the analytics package still provides a consistent interface across platforms. Could use it on Web too.

2023-01-20 20:11 UTC, conrad-vanl commented on packages/apollos-tv-shared/package.json
> +    "@amplitude/react-native": "^2.17.0",
Yes

2023-01-20 20:11 UTC, conrad-vanl commented on packages/apollos-tv-shared/providers/AppProvider.js
> +      <AnalyticsProvider>
Going to resolve this comment and focus on the one above

2023-01-20 20:12 UTC, conrad-vanl commented on packages/apollos-tv-shared/hooks/useAnalytics.js
> +export { useTrack, useIdentify } from '@apollosproject/ui-analytics';
Another way to think about it....

Before this PR TV and App were using a completely different analytics provider and framework. This PR makes it consistent and provides a hook-based mechanism that we can use across all Apollos Code (if we wanted to).

2023-01-20 20:13 UTC, conrad-vanl commented on packages/apollos-ui-analytics/package.json
> -    "@apollo/client": "3.6.9",
yeah there's a peer dependency listed but it's a mistake to not have it in dev as well

2023-01-20 20:14 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/Provider.js
> +  clients = defaultClients,
React community has moved to using this as the standard because it's more vanilla javascripty.

Other then that, no. It's considered a bad practice to reference `AnalyticsProvider.defaultProps` elsewhere, that would be the only difference

2023-01-20 20:15 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/Provider.js
> +      return;
yeah i think this check keeps this useEffect from running if you haven't logged in yet

2023-01-20 20:16 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/Provider.js
> +  useEffect(() => {
They're separate code flows though, I think splitting them out to separate `useEffects` increases readability? Clearer that they're unrelated code?

2023-01-20 20:18 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
>      expect(tree).toMatchSnapshot();
These were existing snapshots ported over, I did not touch them other then adding the `await act` stuff trying to fix the warnings.

`withTrackOnPress` is deprecated code that's only used in one place, I'm not sure it's worth fixing tests.

2023-01-20 20:19 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
>      expect(tree).toMatchSnapshot();
Resolving to clean up discussion list a little, we can discuss above

2023-01-20 20:19 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
>      expect(tree).toMatchSnapshot();
Resolving to clean up discussion list a little, we can discuss above

2023-01-20 20:20 UTC, conrad-vanl commented on templates/mobile/src/analytics/segment.js
> +    writeKey: Config.SEGMENT_KEY || 'rwkfWr0HpIW4eSUZqI30BmcMAdwsVrW0',
key is sharable / not considered a secret. We're using the same segment instance for all apps.

To me this is just like defaulting to `https://production.apollos.app` if a `DATA_URL` isn't provided.

2023-01-20 20:24 UTC, vinnyjth commented on templates/mobile/src/analytics/segment.js
> +    writeKey: Config.SEGMENT_KEY || 'rwkfWr0HpIW4eSUZqI30BmcMAdwsVrW0',
I'm with @calebpanza here. The default value should be in the Config DB `default` church slug. We've been bitten by having defaults in multiple places in the past :)

2023-01-20 20:25 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/Provider.tests.js
> +describe('Provider', () => {
Feel free to try and fix the tests freaking out. I spent hours on it.... if you start searching for this error message you'll eventually end up on a Github issue where one of the last comments is from @redreceipt with no resolution.

As for test coverage, here's the coverage report for the files focused on in this PR:
<img width="585" alt="Screenshot 2023-01-20 at 2 20 34 PM" src="https://user-images.githubusercontent.com/103927/213798303-d7417187-aa01-40de-8df4-162b298b8e11.png">

`Provider.js` is the main focus of texts that I wrote. Those two uncovered line #s that are listed are going to be really hard to capture in valuable tests. Lines 122-123 covers the code that handles reseting a user. I'm not sure how to fake this using Apollo Mocks. As we'd have to render the component once, change the mock, then re-render it. And this wouldn't show up in a snapshot test, so we'd have to just use mocked functions to show that `.reset()` and `.group()` gets called. What's the risk if this code doesn't properly fire? Well, interactions until the user logs in again would be tied to the user that was last logged in.

That second code group - 142-143, cover the deprecated `useTrack` function, which it sounds like we might just remove support for in this PR based on your other comments.

`CoreInteractions` was ported over almost verbatim from TV, which didn't include test coverage. 

The other components are existing components that are untouched by this PR, so I didn't work on test coverage either. I would rather remove those components from our code base then spend time writing tests for them, was just trying to keep this PR smaller. 😅

2023-01-20 21:23 UTC, calebpanza commented on packages/apollos-ui-analytics/package.json
> -    "@apollo/client": "3.6.9",
@conrad-vanl looks like the peer dependency got removed, too. So right now `apollo/client` is _not_ listed in any of the dependencies

2023-01-20 21:25 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.js
> +  useEffect(() => {
In that case, might consider defining each of those using `useCallback` and then just having 1 `useEffect` that fires off each of the separate code flows.

2023-01-20 21:28 UTC, calebpanza commented on packages/apollos-ui-analytics/src/Provider.tests.js
> +describe('Provider', () => {
Ok cool! That makes sense. So for those files that are intended to be deprecated in the near-distant future, maybe we could just mark them with an intent to deprecate. That way we keep track of it and know to not spend tons of time on better coverage and such.

2023-01-20 21:29 UTC, calebpanza commented on packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
>      expect(tree).toMatchSnapshot();
What would it take to remove it from that one place? Then we could just kill the file entirely which would probably help

2023-01-20 21:33 UTC, calebpanza commented
Lol. Hope it's not too much/wildly overwhelming! Really impressed by how much is covered with this PR and just wanna make sure to give it a proper test

2023-01-21 03:05 UTC, conrad-vanl commented on packages/apollos-ui-analytics/package.json
> -    "@apollo/client": "3.6.9",
oh i understand now

2023-01-21 03:06 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/Provider.js
> +  useEffect(() => {
What's wrong with two `useEffect`s?

2023-01-21 03:09 UTC, conrad-vanl commented on templates/mobile/src/analytics/segment.js
> +    writeKey: Config.SEGMENT_KEY || 'rwkfWr0HpIW4eSUZqI30BmcMAdwsVrW0',
@vinnyjth That's fine, but how is this differen't then the way we're doing `APP_DATA_URL` [here](https://github.com/ApollosProject/apollos-apps/blob/master/templates/mobile/src/client/index.js#L26)? That's what I based this code on. I don't think we'd be setting `SEGMENT_KEY` ever except locally, and I do NOT want churches to be able to override and provide their own segment key. This is for our analytics purposes, not theirs'

2023-01-24 18:14 UTC, conrad-vanl commented on packages/apollos-ui-connected/src/DailyHabitsConnected/PrayerExperience/PrayerSwipeScreen.js
> +  const track = useTrack();
There's currently pretty wide-spread usage of `useTrack` and I'd really like to try to avoid refactoring that out in this PR. I feel like it's already big enough. `useContext(...)` was worse and not as supported, and less widespread, so I atleast took those out.

2023-01-24 18:15 UTC, conrad-vanl commented
@calebpanza addressed _most_ of your comments. 

@vinnyjth since Caleb is out didn't know if you wanted to weigh in on the review at all here -> I know segment roll out is lower priority then other things but I'm trying to get a handle on our data which is blocked by this.

2023-01-24 18:48 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/Provider.js
> +    client.group(church); // also called on reset
nice

2023-01-24 18:50 UTC, vinnyjth commented on packages/apollos-ui-prayer/src/PrayerExperienceConnected/index.js
> +  const track = useTrack();
Answered above :) Minimizing amount of code changes.

2023-01-24 18:50 UTC, vinnyjth commented on packages/apollos-ui-prayer/src/screens/AddPrayerScreenConnected/index.js
> +  const track = useTrack();
Answered above :) Minimizing amount of code changes.

2023-01-24 18:50 UTC, vinnyjth commented on packages/apollos-ui-prayer/src/screens/PrayerScreen/index.js
> +  const track = useTrack();
Answered above :) Minimizing amount of code changes.

2023-01-24 18:50 UTC, vinnyjth commented on templates/mobile/src/analytics/onesignal.js
> +export const track = (eventName, properties) => {
I totally forgot we had these

2023-01-24 18:59 UTC, vinnyjth commented on templates/mobile/src/index.js
> +    return 'Unknown';
So we don't risk a red screen error line 153.
```suggestion
    return { name: 'Unknown' };
```

2023-01-24 19:05 UTC, vinnyjth commented on templates/mobile/src/analytics/segment.js
> +    writeKey: Config.SEGMENT_KEY,
this feels like the right choice to me 👍

2023-01-24 19:32 UTC, vinnyjth commented
Seeing a lot of identifies after logging in

2023-01-24 19:32 UTC, vinnyjth commented
https://user-images.githubusercontent.com/1637694/214390491-6931f53c-cf0a-491b-903f-3981f08fea5b.mp4

2023-01-24 19:36 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/Provider.js
> +  }, [client, data?.currentUser?.profile]);
Removing `client` here stops an infinite identify loop from happening. Might be better options? 
```suggestion
  }, [data?.currentUser?.profile]);
```

2023-01-24 19:40 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +const DEVICE_ID = DeviceInfo.getUniqueId();
`getUniqueId` returns a promise - we'll have to refactor slightly

2023-01-24 19:41 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +const DEVICE_ID = DeviceInfo.getUniqueId();
<img width="406" alt="CleanShot 2023-01-24 at 14 40 49@2x" src="https://user-images.githubusercontent.com/1637694/214392285-d0c06230-5040-4d83-a0f0-4553048a1c48.png">

2023-01-24 19:42 UTC, vinnyjth commented on scripts/setup-app.sh
> +SEGMENT_KEY=$(curl -s --fail -H "x-api-key: $APOLLOS_API_KEY" -H "accept: text/plain" "$API_URL/config/$CHURCH/APP.SEGMENT_KEY")
💥

2023-01-24 19:50 UTC, vinnyjth commented
@conrad-vanl Fixed the identity and anonymous ID issues mentioned above, but you'll have to let me know if you care for my approach. 

Only other thing I think this PR needs is a clear way to pass on the church slug, I don't think we want to rely on the app name

2023-01-24 19:54 UTC, vinnyjth commented
Hm - the `group` might be enough but I don't see it in the amplitude debugger. Digging deeper.
<img width="1546" alt="CleanShot 2023-01-24 at 14 54 23@2x" src="https://user-images.githubusercontent.com/1637694/214395175-1af4b51e-0ad4-47fd-85a3-5a52873cf256.png">

2023-01-24 20:00 UTC, conrad-vanl commented
Yeah hoping we can rely on `group` for that, either way we'll want to be able to leverage [Destination Filters](https://segment.com/docs/connections/destinations/destination-filters/) by `church_slug`

2023-01-24 20:03 UTC, vinnyjth commented
I can see the group events flowing through in the segment logs - so maybe it's a syntax issue? 

<img width="1163" alt="CleanShot 2023-01-24 at 15 03 29@2x" src="https://user-images.githubusercontent.com/1637694/214396787-b7593a81-f045-47d9-873d-1200536ce635.png">

2023-01-24 20:09 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
gut check my logic @conrad-vanl 

we'll need to do the same thing in `identify` as well

2023-01-24 20:10 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/Provider.js
> +  church,
@conrad-vanl changed this to not have a default - it's handled above

2023-01-24 20:11 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/Provider.js
> +  }, [church, data?.currentUser?.profile?.id]);
@conrad-vanl I'm noticing that `client` in the deps is causing this hook to fire on every page change. Do you have a better idea here? any ideas on how to make `client` mutate less?

2023-01-24 21:29 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/Provider.js
> +  }, [church, data?.currentUser?.profile?.id]);
🤔

2023-01-25 02:20 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
@vinnyjth do we need this ID? 
https://github.com/react-native-device-info/react-native-device-info#getuniqueid

Also, how is this being used? Do we really want https://github.com/react-native-device-info/react-native-device-info#getdeviceid instead?

2023-01-25 02:23 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
Really I think we should turn `track` into a promise and await deviceId

2023-01-25 02:29 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/Provider.js
> +  }, [church, data?.currentUser?.profile?.id]);
I bet it has something to do with how `clientsWithDefaults` is getting constructed. This wasn't happening originally, and when I started implementing/fix on TV I changed this up quite a bit. I have an idea

2023-01-25 02:37 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
If we're trying to implement `anonymousId` I think we really need `uniqueId`. Refactoring as a promise sound great 👍

2023-01-25 02:45 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
what do we need `anonymousId` though? 

We don't use it in the [Rock Interactions interface](https://github.com/ApollosProject/apollos-cluster/blob/master/src/data/analytics/interfaces/rock_interactions.js).

We do in Segment, but only crsds tv uses segment, and only on their TV app.

On Third Thought, WDYT about just removing core analytics?

I know it doesn't account for a lot of server time but it seems like dead code.

When we port Crsds TV over to Core TV, we'll just wire up their segment key on the frontend -> we can have two segment libraries installed at once so what we'll do is add support for a second segment key (or use our segment instance to forward segment events to theirs, if it can)

2023-01-25 02:52 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
Was thinking the same thing myself...  especially now that we're implementing segment. 

Can we confirm that the "VIEW" interaction is fired when viewing content items _without_ core analytics?

2023-01-25 02:53 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
sure, that's an INTERACTION not an analytics event :) 

I was getting the two confused

2023-01-25 02:54 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
I think we might be relying on the analytics event creating an interaction as a side effect for that particular interaction though, would need to dig to confirm.

2023-01-25 02:55 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
I don't think there's a VIEW interaction, just a COMPLETE

2023-01-25 02:58 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
yah here it is 

https://github.com/ApollosProject/apollos-apps/blob/283a5a3db7c26a93826c844ee1ae6bb812e9c3e7/templates/mobile/src/content/ContentSingleConnected/ContentSingle.js#L30-L46 which calls a method here https://github.com/ApollosProject/apollos-cluster/blob/master/src/data/analytics/interfaces/rock_interactions.js#L30 which... doesn't exist. 

yah safe to say we can remove it :) how are `VIEW` interactions being created?

2023-01-25 03:00 UTC, conrad-vanl commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
I was about to say there's not `VIEW` interactions, but I do see them. only on `VideoMedia` though. Probably in the video player

2023-01-25 03:01 UTC, vinnyjth commented on packages/apollos-ui-analytics/src/CoreAnalaytics.js
> +  useEffect(() => {
lol, didn't see the comments you added before I went digging. Looks like we create VIEW interactions on Scripture and Media. So yah - I vote we kill the core analytics functions.

2023-02-01 02:08 UTC, calebpanza commented
Trying to catch up on the progress made here. How can I help?

2023-02-01 02:24 UTC, conrad-vanl commented
Hit the green approve button? Lol. I think it's ready....

2023-02-10 04:53 UTC, conrad-vanl commented
@calebpanza @vinnyjth anything else you want to see on this?

2023-02-10 14:16 UTC, calebpanza commented
@conrad-vanl events are coming through on mobile. I don't see the "prayed for prayer" interaction coming through, though. Do we want a fast follow up for user interactions auditing or get it done here?

2023-02-10 14:21 UTC, conrad-vanl commented
Are you confusing interactions and analytics?

This does not touch interactions

2023-02-10 15:25 UTC, calebpanza commented
I guess to reword my question: are we intending to use Segment for interaction data as well? I'm noticing that interaction data is not being forwarded to Segment

2023-02-10 15:27 UTC, conrad-vanl commented
Correct. We are not currently forwarding interaction data to segment. This PR is intended to be a 1:1 replacement of current analytics without touching interacitons.

In most cases, we're sending both an analytic event and an interaction and so making this PR handle all interactions as well would result in double events being sent.

The intention would be to follow up with those things in subsequent PRs.

2023-02-10 15:32 UTC, calebpanza commented
ok perfect! Just wanted to confirm. I think I'm good with this, then

2023-02-10 15:32 UTC, calebpanza approved these changes

2023-02-10 15:32 UTC, merged