check in
ApollosProject/apollos-apps pull request #2820
Opened 2022-12-01 21:05 UTC by calebpanza

## ✏️ Description

## 🔬 To Test
1.
2.

## 📸 Screenshots

## ⚠️ To-do Before Merge

## 📝 Checklist

- [ ] I have performed a self-review of my code
- [ ] I have tested my code works in the project (nothing breaks)
- [ ] I have commented my code in hard-to-understand areas
- [ ] New and existing tests and linting pass locally with my changes
- [ ] I have made corresponding changes to the documentation (new envs?)
- [ ] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

2022-12-01 21:26 UTC, vinnyjth requested changes
I'm mild skeptical about the need to pass the `dd-mm-yyyy` string instead of a timestamp, but I'll send that feedback in the api PR

2022-12-01 21:26 UTC, vinnyjth commented on templates/mobile/src/utils/useDailyHabits.js
> +  console.log(streak.map(({ date }) => date));
```suggestion
```

2022-12-01 21:26 UTC, vinnyjth commented on templates/mobile/src/utils/useDailyHabits.js
> +  console.log({
remove this comment :)

2022-12-01 21:26 UTC, vinnyjth commented on templates/mobile/src/utils/useDailyHabits.js
> +function formatWithTimeZone(date) {
isn't this "format without time zone?" 

maybe better expressed as `formatLocalDate`?

2022-12-01 22:09 UTC, calebpanza commented
> I'm mild skeptical about the need to pass the dd-mm-yyyy string instead of a timestamp

Totally understand. It's a bit too much information for the date parsers to handle and we would end up using Regex on the server to just pull that specific bit out anyway. Check out the API logic cause it provides a LOT more context

2022-12-02 19:35 UTC, dsilva609 approved these changes

2022-12-02 21:56 UTC, merged