feat(follow): update follow language
ApollosProject/apollos-apps pull request #2895
Opened 2023-01-05 21:25 UTC by dsilva609

## ✏️ Description
- Updates language to follow a user to better reflect flow

## 🔬 To Test
1. Go to individual prayer
2. Tap three vertical dot button
3. Should see `Request to follow [User]` in the menu

## 📸 Screenshots
![image](https://user-images.githubusercontent.com/7557597/210882559-668b46bc-a216-4687-8bd7-20fecc2db3c1.png)

## ⚠️ To-do Before Merge

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

2023-01-05 21:26 UTC, dsilva609 commented
Updated it to say `Request to Follow [User]` but I'm not sure how much we should worry about sizing especially if there's much longer first name.

2023-01-06 20:29 UTC, vinnyjth approved these changes

2023-01-07 02:18 UTC, calebpanza requested changes
@dsilva609 after seeing this in practice, I think that we'd be better suited using "Follow [user]" as the button text, but then updating the _alert_ to more accurately reflect the response from the server. If "FOLLOW" is sent back, "Great! You're following them" but if "REQUESTED" then "You've requested to follow them"

2023-01-09 18:11 UTC, dsilva609 commented
> 

@calebpanza Swapped it back to the original button text and cleaned up the alert text to include the requester user name as well for more clarity.

2023-01-09 19:20 UTC, calebpanza approved these changes

2023-01-09 19:20 UTC, merged