feat(video): add interactions for pausing, rewinding, and exiting videos
ApollosProject/apollos-apps pull request #2901
Opened 2023-01-11 14:58 UTC by dsilva609

## ✏️ Description
- adds interactions to handle watch states when a user
 - rewinds
 - pauses
 - exits 

## 🔬 To Test
1. start a video
2. pause (should create an interaction)
3. rewind (should create an interaction)
4. exit video (should create an interation)

## 📸 Screenshots

## ⚠️ To-do Before Merge

## 📝 Checklist

- [x] I have performed a self-review of my code
- [x] I have tested my code works in the project (nothing breaks)
- [x] I have commented my code in hard-to-understand areas
- [x] New and existing tests and linting pass locally with my changes
- [x] I have made corresponding changes to the documentation (new envs?)
- [x] For PR's with design updates/changes, I have consulted with the product designer and made all necessary adjustments in Figma

2023-01-11 20:25 UTC, calebpanza commented on templates/tv/ios/Podfile.lock
> +  glog: 5b768715ae7bf8149e9d269089c22585cee27eb7
Any idea why the Podfile would have changed in this?

2023-01-11 20:25 UTC, calebpanza commented on templates/tv/ios/Podfile.lock
> +  glog: 5b768715ae7bf8149e9d269089c22585cee27eb7
never mind. Just saw your commit

2023-01-12 17:12 UTC, calebpanza commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
So I _think_ the way that this should be handled would be:

handleVideoExited ==> `useCallback` with `currentTime` as as dependency
useEffect has `handleVideoExited` as a dependency

Something about this flow atm doesn't quite make sense to me

2023-01-12 17:12 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
> +      return elapsedTime?.toFixed(0) === videoDuration;
maybe `>=` just in case something gets mismatched for some reason. Makes it more exhaustive of a check

2023-01-12 18:28 UTC, dsilva609 commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
goal here was to try to get the final interaction when the video unmounts, currently it triggers too often instead of just once

2023-01-12 19:11 UTC, dsilva609 commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
> +      return elapsedTime?.toFixed(0) === videoDuration;
good catch 👍

2023-01-12 19:53 UTC, calebpanza commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
Oh I see. So basically the equivalent of "componentDidUnmount"? But wouldn't that trigger if the screen caused a rerender for some reason? The users didn't actually "exit" the video in that case and we could end up with messy data?

2023-01-12 19:55 UTC, dsilva609 commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
Yeah that's what I was trying to do. Looking into it more, this might be something that the parent component would have to handle like if the video content `isFocused` or not and just save the interaction at that point

2023-01-12 20:00 UTC, calebpanza commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
We could listen to "on app background" and "on navigation" and it would accomplish the same thing, right?

2023-01-12 20:01 UTC, calebpanza commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
We could also cut this from scope if it's too much. We'll always be covered within a 10 second window of where the user left off even if we don't store play head on exit and I'm fine with that as an option too

2023-01-12 20:15 UTC, dsilva609 commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
Yeah this specific watch state might be a little more involved than I initially thought. I'd be okay will cutting this one out if it does become too much.

2023-01-12 21:37 UTC, dsilva609 commented on packages/apollos-tv-shared/components/VideoPlayer/VideoPlayer.js
> +  useEffect(() => {
removing it for now as it's not behaving as expected

2023-01-13 17:30 UTC, calebpanza requested changes
@dsilva609 Fast Forward and Rewind are _not_ working as expected on mobile.

1. Play video --> interaction
2. Press Fast Forward --> NO interaction
3. Press Rewind --> NO interaction
4. Pause --> interaction

I would expect an interaction to be written for steps 2 and 3

On mobile, there is no interaction being triggered for the 10 second interval

1. Play video --> interaction
2. Allow 10 seconds of the video to play --> NO interaction
3. Allow more seconds of the video to play --> NO interaction
4. Video completes --> interaction

Again, for steps 2 and 3 I would expect an interaction to be triggered

2023-01-13 17:30 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
>        interactWithVideo({
At the definition of this hook, we should optimistically respond from the server and then manually update the local cache with the playhead information wherever we're querying for user progress (I think on the content item).

If you need examples of where to do this, I just recently implemented this on the [useCompleteNode hook](https://github.com/ApollosProject/apollos-apps/blob/master/templates/mobile/src/utils/useCompleteNode.js)

2023-01-13 21:19 UTC, dsilva609 commented
@calebpanza added an `onProgress` event to the mobile video component. Seems like that will be able to start handling playhead changes.

2023-01-13 21:48 UTC, dsilva609 commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
>        interactWithVideo({
Would this be to help handle showing the correct progress bar percentage?

2023-01-17 16:00 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
>        interactWithVideo({
This would help save us from having old data stored in the cache. It also keeps us from _having_ to re-query every time we want to know the user progress. Instead of `interactWithVideo` using `refetchQueries` in order to get the local cache state updated to reflect, we manually set it in good faith that our interaction was stored.

2023-01-17 16:01 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
>        interactWithVideo({
You make all network traffic effectively a background process at that point

2023-01-17 18:00 UTC, calebpanza requested changes

2023-01-17 18:00 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
> +      if ((elapsedTime - currentPlayhead).toFixed(0) >= 10) {
Let's get this `10` pulled out as a constant at the top of the file for easier access/visibility later on. Could even leave a comment that this is the default duration or something.

2023-01-17 18:40 UTC, dsilva609 commented on packages/apollos-ui-media-player/src/Container.tsx
> +  React.useEffect(() => {
Can definitely be done. Noticed that there's a lot of `React.[something]` in this file

2023-01-17 18:44 UTC, dsilva609 commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
> +      if ((elapsedTime - currentPlayhead).toFixed(0) >= 10) {
done

2023-01-17 18:44 UTC, dsilva609 commented on packages/apollos-ui-media-player/src/Container.tsx
> +  React.useEffect(() => {
done

2023-01-17 19:09 UTC, dsilva609 commented on packages/apollos-ui-media-player/src/Container.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
fixed and updated the other useEffects as well

2023-01-17 20:07 UTC, dsilva609 commented on packages/apollos-ui-media-player/src/Container.tsx
> +    onProgress({ elapsedTime, totalDuration, ...analyticsMeta });
@calebpanza  wrapped the `onProgress` call in a try catch and wrapped that in a 1 second throttle

2023-01-17 21:28 UTC, calebpanza commented on packages/apollos-ui-media-player/src/Container.tsx
> +    throttle((elapsedTime, totalDuration) => {
I see a warning here prompting an inline function to be used instead of passing `throttle` directly. Something about React not being able to handle the dependencies properly without. I think if you did `() => throttle(...)` that would do it. I also wonder if you even need the `useCallback` along with the throttle. Might be redundant and cause some issues?

2023-01-17 21:28 UTC, calebpanza commented on packages/apollos-ui-media-player/src/Container.tsx
> +    throttle((elapsedTime, totalDuration) => {
I think we could probably get away with this being every `500` milliseconds

2023-01-18 00:30 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
> +const INTERACTION_THROTTLE_SECONDS = 1000 * 1;
Could just name it "MILLISECONDS" and not have to worry about the multiplication

2023-01-18 00:30 UTC, calebpanza commented on packages/apollos-ui-media-player/src/Container.tsx
> +const PROGRESS_THROTTLE_SECONDS = 1000 * 0.5;
Same thing here about naming

2023-01-18 14:01 UTC, dsilva609 commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
> +const INTERACTION_THROTTLE_SECONDS = 1000 * 1;
I can update that. My thought was to try to keep a consistent unit of time with all the constants

2023-01-18 14:34 UTC, dsilva609 commented on packages/apollos-ui-media-player/src/Container.tsx
> +    throttle((elapsedTime, totalDuration) => {
Tried a few different ways if calling the throttle and it seems that only wrapping it a callback like this works at the moment. Having it inside the `useEffect` had it so it never triggered, having it just as `throttle(...)` strangely made it execute more often.

2023-01-18 14:41 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/index.js
> +const INTERACTION_THROTTLE_SECONDS = 1000 * 1;
Yeah I feel that. I wouldn't worry about that, though. The trottle method expects milliseconds, so let's just go with that

2023-01-18 14:42 UTC, calebpanza approved these changes

2023-01-20 14:21 UTC, dsilva609 commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/useSetVideoProgress.js
> +export default function useSaveVideoInteraction(videoId) {
leaving a reminder to rename this to match the file name

2023-01-20 14:26 UTC, calebpanza commented on packages/apollos-ui-connected/src/ApollosPlayerConnected/useSetVideoProgress.js
> +export default function useSaveVideoInteraction(videoId) {
resolved!

2023-01-20 14:27 UTC, calebpanza approved these changes
@dsilva609 once you do another quick gut check, I'm good to get this merged!

2023-01-20 21:01 UTC, dsilva609 commented on packages/apollos-tv-shared/hooks/useVideoMediaProgress.js
> +      playhead: 0,
@calebpanza is this intended to be 0?

2023-01-20 21:35 UTC, calebpanza commented on packages/apollos-tv-shared/hooks/useVideoMediaProgress.js
> +      playhead: 0,
Only if there is no value given. In the case that the _entire_ `userProgress` object is missing from the resolved data, at least we have a valid object to avoid missing property references

2023-01-20 21:40 UTC, merged